[package]
name = "nimbus-oci"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nimbus-store = { path = "../nimbus-store" }
tokio.workspace = true
serde.workspace = true
serde_json = "1.0"
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
hex.workspace = true
reqwest = { workspace = true, features = ["gzip"] }
flate2.workspace = true
tar.workspace = true
tokio-util = "0.7"
async-trait.workspace = true
base64 = "0.22"
rkyv.workspace = true

[dev-dependencies]
tempfile = "3.10"