// Copyright 2026 Mohammed Boukaba.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"log"
	"time"

	runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1"
	pullrunruntime "pullrun/protoapi/pullrun/runtime"
)

// newContainerID generates a random 24-hex-char CRI container id.
func newContainerID() string {
	b := make([]byte, 12)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("pullrun-%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

// ============================================================
// Container service — real per-container workloads.
//
// Every CRI container is a Pullrun workload running its own image:
//   - container backend: joins the sandbox's network namespace
//     (network_mode "container:<sandbox workload id>") — the pod model.
//   - vm backend: runs as an independent bridged workload in the pod's
//     per-pod bridge (VMs cannot share a network namespace).
// ============================================================

// containerWorkloadID derives a stable pullrun workload id from a CRI
// container id. The runtime accepts [a-zA-Z0-9._-] ids only.
func containerWorkloadID(containerID string) string {
	if len(containerID) > 20 {
		containerID = containerID[len(containerID)-20:]
	}
	return "c-" + containerID
}

// seccompProfileFor maps a CRI seccomp profile to a pullrun profile:
//   - RuntimeDefault → "" (daemon policy default allowlist)
//   - Unconfined → "unconfined"
//   - Localhost (predefined node profiles) → unsupported; the daemon
//     policy default is used and a warning is logged.
func seccompProfileFor(profile runtimeapi.SecurityProfile_ProfileType) string {
	switch profile {
	case runtimeapi.SecurityProfile_RuntimeDefault:
		return ""
	case runtimeapi.SecurityProfile_Unconfined:
		return "unconfined"
	default:
		log.Printf("warning: localhost seccomp profiles are not resolvable by pullrun; using daemon policy default")
		return ""
	}
}

// runRequestForContainer builds the RunRequest that executes this
// container's own image in the pod. `cid` is the CRI container id
// (generated by the shim; used to derive the workload id).
func (c *criServer) runRequestForContainer(cid string, req *runtimeapi.CreateContainerRequest, sandbox *sandboxRecord, rootDigest string) (*pullrunruntime.RunRequest, error) {
	cfg := req.Config

	backend := backendForRuntimeHandler(sandbox.runtimeClass)
	netMode := "container:" + sandbox.pullrunID
	if backend == "vm" {
		// VMs cannot join another workload's network namespace; run in
		// the pod's per-pod bridge instead.
		netMode = "bridge"
	}
	if sandbox.hostNetwork {
		netMode = "host"
	}

	// Command: CRI separates entrypoint (Command) from args (Args).
	command := append([]string{}, cfg.Command...)
	command = append(command, cfg.Args...)

	env := make(map[string]string, len(cfg.Envs))
	for _, e := range cfg.Envs {
		env[e.Key] = e.Value
	}

	// Resources: mirror the CRI Linux container resources.
	var cpu uint64
	var mem uint64
	if l := cfg.GetLinux(); l != nil {
		if r := l.GetResources(); r != nil {
			if r.CpuPeriod > 0 && r.CpuQuota > 0 {
				cpu = uint64(float64(r.CpuQuota) / float64(r.CpuPeriod) * 1000)
			}
			if r.MemoryLimitInBytes > 0 {
				mem = uint64(r.MemoryLimitInBytes)
			}
		}
	}

	// Security context.
	var privileged bool
	var readonly bool
	var noNewPrivs bool
	var seccomp string
	if sc := cfg.GetLinux().GetSecurityContext(); sc != nil {
		privileged = sc.Privileged
		readonly = sc.GetReadonlyRootfs()
		noNewPrivs = sc.GetNoNewPrivs()
		if p := sc.GetSeccomp(); p != nil {
			seccomp = seccompProfileFor(p.ProfileType)
		}
	}

	// Mounts: CRI volumes arrive as host paths (kubelet prepares
	// hostPath/EmptyDir dirs itself), so every mount is a bind mount.
	mounts := make([]*pullrunruntime.Mount, 0, len(cfg.Mounts))
	for _, m := range cfg.Mounts {
		opts := []string{"rbind", "rprivate"}
		if m.Readonly {
			opts = append(opts, "ro")
		}
		mounts = append(mounts, &pullrunruntime.Mount{
			Type:        "bind",
			Source:      m.HostPath,
			Destination: m.ContainerPath,
			Options:     opts,
		})
	}

	return &pullrunruntime.RunRequest{
		Id:              containerWorkloadID(cid),
		RootDigest:      rootDigest,
		Backend:         backend,
		Command:         command,
		Env:             env,
		CpuMillicores:   cpu,
		MemoryBytes:     mem,
		NetworkMode:     netMode,
		WorkingDir:      cfg.WorkingDir,
		BridgeName:      sandbox.bridgeName,
		Mounts:          mounts,
		Privileged:      privileged,
		ReadonlyRootfs:  readonly,
		NoNewPrivileges: noNewPrivs,
		SeccompProfile:  seccomp,
		Dns:             sandbox.dns,
	}, nil
}

func (c *criServer) CreateContainer(ctx context.Context, req *runtimeapi.CreateContainerRequest) (*runtimeapi.CreateContainerResponse, error) {
	if req.PodSandboxId == "" {
		return nil, fmt.Errorf("CreateContainer: missing PodSandboxId")
	}
	if req.Config == nil || req.Config.Metadata == nil {
		return nil, fmt.Errorf("CreateContainer: missing container config/metadata")
	}
	sandbox, ok := c.sandboxStore.getSandbox(req.PodSandboxId)
	if !ok {
		return nil, fmt.Errorf("CreateContainer: sandbox %q not found", req.PodSandboxId)
	}
	if sandbox.state != runtimeapi.PodSandboxState_SANDBOX_READY {
		return nil, fmt.Errorf("CreateContainer: sandbox %q is not ready (state=%v)", req.PodSandboxId, sandbox.state)
	}

	image := req.Config.Image.Image

	// The CRI runtime generates the container id; kubelet echoes it back.
	cid := newContainerID()

	// Pull the container's own image (HasImage fast path first).
	rootDigest, err := c.ensureImage(ctx, image, "")
	if err != nil {
		return nil, fmt.Errorf("CreateContainer: %w", err)
	}

	runReq, err := c.runRequestForContainer(cid, req, sandbox, rootDigest)
	if err != nil {
		return nil, err
	}

	runCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	runResp, err := c.runtimeClient.RunWorkload(runCtx, runReq)
	cancel()
	if err != nil {
		return nil, fmt.Errorf("CreateContainer: run workload: %w", err)
	}

	rec := &containerRecord{
		id:        cid,
		sandboxID: req.PodSandboxId,
		pullrunID: runResp.Id,
		name:      req.Config.Metadata.Name,
		image:     image,
		imageRef:  rootDigest,
		createdAt: time.Now(),
		state:     runtimeapi.ContainerState_CONTAINER_CREATED,
	}
	c.sandboxStore.putContainer(rec)

	log.Printf("CreateContainer id=%s sandbox=%s workload=%s image=%s net=%s",
		cid, req.PodSandboxId, runResp.Id, image, runReq.NetworkMode)
	return &runtimeapi.CreateContainerResponse{ContainerId: cid}, nil
}

func (c *criServer) StartContainer(ctx context.Context, req *runtimeapi.StartContainerRequest) (*runtimeapi.StartContainerResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("StartContainer: container %q not found", req.ContainerId)
	}

	// The workload was launched at CreateContainer; verify it is actually
	// running before reporting success.
	getCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	wl, err := c.runtimeClient.GetWorkload(getCtx, &pullrunruntime.GetWorkloadRequest{Id: rec.pullrunID})
	cancel()
	if err != nil {
		return nil, fmt.Errorf("StartContainer: %w", err)
	}
	switch wl.State {
	case "running", "created", "scheduled":
	case "exited", "stopped":
		return nil, fmt.Errorf("StartContainer: container %q exited before start (code=%d)", req.ContainerId, wl.ExitCode)
	default:
		return nil, fmt.Errorf("StartContainer: container %q in unexpected state %q", req.ContainerId, wl.State)
	}

	rec.state = runtimeapi.ContainerState_CONTAINER_RUNNING
	rec.startedAt = time.Now()
	rec.exitCode = 0
	c.sandboxStore.putContainer(rec)

	log.Printf("StartContainer id=%s workload=%s running", req.ContainerId, rec.pullrunID)
	return &runtimeapi.StartContainerResponse{}, nil
}

func (c *criServer) StopContainer(ctx context.Context, req *runtimeapi.StopContainerRequest) (*runtimeapi.StopContainerResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("StopContainer: container %q not found", req.ContainerId)
	}
	if rec.state == runtimeapi.ContainerState_CONTAINER_EXITED || rec.state == runtimeapi.ContainerState_CONTAINER_UNKNOWN {
		// Idempotent: already stopped.
		return &runtimeapi.StopContainerResponse{}, nil
	}

	stopCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	_, err := c.runtimeClient.StopWorkload(stopCtx, &pullrunruntime.StopRequest{Id: rec.pullrunID})
	cancel()
	if err != nil {
		return nil, fmt.Errorf("stop workload: %w", err)
	}

	rec.state = runtimeapi.ContainerState_CONTAINER_EXITED
	if rec.exitCode == 0 {
		rec.exitCode = 137
	}
	c.sandboxStore.putContainer(rec)

	log.Printf("StopContainer id=%s (stopped workload %s)", req.ContainerId, rec.pullrunID)
	return &runtimeapi.StopContainerResponse{}, nil
}

func (c *criServer) RemoveContainer(ctx context.Context, req *runtimeapi.RemoveContainerRequest) (*runtimeapi.RemoveContainerResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if ok && rec.state == runtimeapi.ContainerState_CONTAINER_RUNNING {
		stopCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
		_, _ = c.runtimeClient.StopWorkload(stopCtx, &pullrunruntime.StopRequest{Id: rec.pullrunID})
		cancel()
	}
	c.sandboxStore.removeContainer(req.ContainerId)
	log.Printf("RemoveContainer id=%s", req.ContainerId)
	return &runtimeapi.RemoveContainerResponse{}, nil
}

func (c *criServer) ContainerStatus(ctx context.Context, req *runtimeapi.ContainerStatusRequest) (*runtimeapi.ContainerStatusResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("ContainerStatus: container %q not found", req.ContainerId)
	}

	state := rec.state
	exitCode := rec.exitCode
	startedAt := rec.startedAt.UnixNano()

	// Query the live state of the underlying workload.
	getCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	wl, err := c.runtimeClient.GetWorkload(getCtx, &pullrunruntime.GetWorkloadRequest{Id: rec.pullrunID})
	cancel()
	if err == nil {
		switch wl.State {
		case "created", "scheduled":
			state = runtimeapi.ContainerState_CONTAINER_CREATED
		case "running":
			state = runtimeapi.ContainerState_CONTAINER_RUNNING
		case "exited", "stopped":
			state = runtimeapi.ContainerState_CONTAINER_EXITED
			exitCode = int32(wl.ExitCode)
		default:
			state = runtimeapi.ContainerState_CONTAINER_UNKNOWN
		}
	}

	status := &runtimeapi.ContainerStatus{
		Id:        rec.id,
		Metadata:  &runtimeapi.ContainerMetadata{Name: rec.name},
		State:     state,
		CreatedAt: rec.createdAt.UnixNano(),
		Image:     &runtimeapi.ImageSpec{Image: rec.image},
		ImageRef:  rec.imageRef,
	}
	if startedAt > 0 {
		status.StartedAt = startedAt
	}
	if state == runtimeapi.ContainerState_CONTAINER_EXITED {
		status.ExitCode = exitCode
	}

	return &runtimeapi.ContainerStatusResponse{Status: status}, nil
}

func (c *criServer) ListContainers(ctx context.Context, req *runtimeapi.ListContainersRequest) (*runtimeapi.ListContainersResponse, error) {
	items := c.sandboxStore.listContainers(req.Filter)
	return &runtimeapi.ListContainersResponse{Containers: items}, nil
}

func (c *criServer) UpdateContainerResources(ctx context.Context, req *runtimeapi.UpdateContainerResourcesRequest) (*runtimeapi.UpdateContainerResourcesResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("UpdateContainerResources: container %q not found", req.ContainerId)
	}

	cpu := uint64(0)
	mem := uint64(0)
	if req.Linux != nil {
		if req.Linux.CpuPeriod > 0 && req.Linux.CpuQuota > 0 {
			cpu = uint64(float64(req.Linux.CpuQuota) / float64(req.Linux.CpuPeriod) * 1000)
		}
		if req.Linux.MemoryLimitInBytes > 0 {
			mem = uint64(req.Linux.MemoryLimitInBytes)
		}
	}

	updCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	_, err := c.runtimeClient.UpdateWorkload(updCtx, &pullrunruntime.UpdateWorkloadRequest{
		Id:            rec.pullrunID,
		CpuMillicores: cpu,
		MemoryBytes:   mem,
	})
	cancel()

	if err != nil {
		log.Printf("UpdateContainerResources id=%s (runtime error: %v)", req.ContainerId, err)
	} else {
		log.Printf("UpdateContainerResources id=%s cpu=%d mem=%d", req.ContainerId, cpu, mem)
	}
	return &runtimeapi.UpdateContainerResourcesResponse{}, nil
}

func (c *criServer) ReopenContainerLog(ctx context.Context, req *runtimeapi.ReopenContainerLogRequest) (*runtimeapi.ReopenContainerLogResponse, error) {
	return &runtimeapi.ReopenContainerLogResponse{}, nil
}

func (c *criServer) PortForward(ctx context.Context, req *runtimeapi.PortForwardRequest) (*runtimeapi.PortForwardResponse, error) {
	sandbox, ok := c.sandboxStore.getSandbox(req.PodSandboxId)
	if !ok {
		return nil, fmt.Errorf("PortForward: sandbox %q not found", req.PodSandboxId)
	}

	port := int32(0)
	if len(req.Port) > 0 {
		port = req.Port[0]
	}

	_, url := c.streaming.newPortForwardSession(sandbox.pullrunID, sandbox.internalIP, port)
	log.Printf("PortForward sandbox=%s ip=%s port=%d url=%s", req.PodSandboxId, sandbox.internalIP, port, url)
	return &runtimeapi.PortForwardResponse{Url: url}, nil
}

func (c *criServer) ExecSync(ctx context.Context, req *runtimeapi.ExecSyncRequest) (*runtimeapi.ExecSyncResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("ExecSync: container %q not found", req.ContainerId)
	}

	execCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	resp, err := c.runtimeClient.ExecInWorkload(execCtx, &pullrunruntime.ExecRequest{
		Id:      rec.pullrunID,
		Command: req.Cmd,
	})
	cancel()
	if err != nil {
		return nil, fmt.Errorf("exec: %w", err)
	}

	return &runtimeapi.ExecSyncResponse{
		Stdout:   resp.Stdout,
		Stderr:   resp.Stderr,
		ExitCode: resp.ExitCode,
	}, nil
}

func (c *criServer) Exec(ctx context.Context, req *runtimeapi.ExecRequest) (*runtimeapi.ExecResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("Exec: container %q not found", req.ContainerId)
	}

	_, url := c.streaming.newSession(rec.pullrunID, req.Cmd, nil, "", false)
	log.Printf("Exec id=%s cmd=%v url=%s", req.ContainerId, req.Cmd, url)
	return &runtimeapi.ExecResponse{Url: url}, nil
}

func (c *criServer) Attach(ctx context.Context, req *runtimeapi.AttachRequest) (*runtimeapi.AttachResponse, error) {
	rec, ok := c.sandboxStore.getContainer(req.ContainerId)
	if !ok {
		return nil, fmt.Errorf("Attach: container %q not found", req.ContainerId)
	}

	_, url := c.streaming.newSession(rec.pullrunID, nil, nil, "", true)
	log.Printf("Attach id=%s url=%s", req.ContainerId, url)
	return &runtimeapi.AttachResponse{Url: url}, nil
}
