// Copyright 2026 Mohammed Boukaba.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: pullrun/runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_PullImage_FullMethodName        = "/pullrun.runtime.Runtime/PullImage"
	Runtime_RunWorkload_FullMethodName      = "/pullrun.runtime.Runtime/RunWorkload"
	Runtime_StopWorkload_FullMethodName     = "/pullrun.runtime.Runtime/StopWorkload"
	Runtime_GetWorkload_FullMethodName      = "/pullrun.runtime.Runtime/GetWorkload"
	Runtime_ListWorkloads_FullMethodName    = "/pullrun.runtime.Runtime/ListWorkloads"
	Runtime_StreamLogs_FullMethodName       = "/pullrun.runtime.Runtime/StreamLogs"
	Runtime_StreamEvents_FullMethodName     = "/pullrun.runtime.Runtime/StreamEvents"
	Runtime_ExecInWorkload_FullMethodName   = "/pullrun.runtime.Runtime/ExecInWorkload"
	Runtime_InspectWorkload_FullMethodName  = "/pullrun.runtime.Runtime/InspectWorkload"
	Runtime_AttachWorkload_FullMethodName   = "/pullrun.runtime.Runtime/AttachWorkload"
	Runtime_HasImage_FullMethodName         = "/pullrun.runtime.Runtime/HasImage"
	Runtime_ListImages_FullMethodName       = "/pullrun.runtime.Runtime/ListImages"
	Runtime_RemoveImage_FullMethodName      = "/pullrun.runtime.Runtime/RemoveImage"
	Runtime_DagStoreInfo_FullMethodName     = "/pullrun.runtime.Runtime/DagStoreInfo"
	Runtime_PortForward_FullMethodName      = "/pullrun.runtime.Runtime/PortForward"
	Runtime_UpdateWorkload_FullMethodName   = "/pullrun.runtime.Runtime/UpdateWorkload"
	Runtime_GetWorkloadStats_FullMethodName = "/pullrun.runtime.Runtime/GetWorkloadStats"
	Runtime_BuildImage_FullMethodName       = "/pullrun.runtime.Runtime/BuildImage"
	Runtime_PushImage_FullMethodName        = "/pullrun.runtime.Runtime/PushImage"
	Runtime_ExportImage_FullMethodName      = "/pullrun.runtime.Runtime/ExportImage"
	Runtime_ImportImage_FullMethodName      = "/pullrun.runtime.Runtime/ImportImage"
	Runtime_RunCompose_FullMethodName       = "/pullrun.runtime.Runtime/RunCompose"
	Runtime_CopyFile_FullMethodName         = "/pullrun.runtime.Runtime/CopyFile"
	Runtime_CommitImage_FullMethodName      = "/pullrun.runtime.Runtime/CommitImage"
	Runtime_DiffWorkload_FullMethodName     = "/pullrun.runtime.Runtime/DiffWorkload"
	Runtime_RuntimeInfo_FullMethodName      = "/pullrun.runtime.Runtime/RuntimeInfo"
	Runtime_CreateNetwork_FullMethodName    = "/pullrun.runtime.Runtime/CreateNetwork"
	Runtime_RemoveNetwork_FullMethodName    = "/pullrun.runtime.Runtime/RemoveNetwork"
	Runtime_ListNetworks_FullMethodName     = "/pullrun.runtime.Runtime/ListNetworks"
	Runtime_Prune_FullMethodName            = "/pullrun.runtime.Runtime/Prune"
	Runtime_Gc_FullMethodName               = "/pullrun.runtime.Runtime/Gc"
	Runtime_CreateSecret_FullMethodName     = "/pullrun.runtime.Runtime/CreateSecret"
	Runtime_ListSecrets_FullMethodName      = "/pullrun.runtime.Runtime/ListSecrets"
	Runtime_InspectSecret_FullMethodName    = "/pullrun.runtime.Runtime/InspectSecret"
	Runtime_RemoveSecret_FullMethodName     = "/pullrun.runtime.Runtime/RemoveSecret"
	Runtime_CreateConfig_FullMethodName     = "/pullrun.runtime.Runtime/CreateConfig"
	Runtime_ListConfigs_FullMethodName      = "/pullrun.runtime.Runtime/ListConfigs"
	Runtime_InspectConfig_FullMethodName    = "/pullrun.runtime.Runtime/InspectConfig"
	Runtime_RemoveConfig_FullMethodName     = "/pullrun.runtime.Runtime/RemoveConfig"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	RunWorkload(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	StopWorkload(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadStatus, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	ExecInWorkload(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	InspectWorkload(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	// Interactive attach to a workload's stdio. The first request
	// opens the stream; subsequent messages carry stdin/eof
	// (client -> server) and stdout/stderr/exit (server -> client).
	// Used by `pullrun workload run alpine:3.18 -- /bin/sh` and
	// similar interactive workloads on microVM backends.
	AttachWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachMessage, AttachMessage], error)
	// Image management
	HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	DagStoreInfo(ctx context.Context, in *DagStoreInfoRequest, opts ...grpc.CallOption) (*DagStoreInfoResponse, error)
	// Port forwarding
	PortForward(ctx context.Context, in *PortForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortForwardData], error)
	// Workload resource updates
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error)
	// Workload statistics
	GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*WorkloadStats, error)
	// Build an OCI image from a Dockerfile and import into the
	// DAG store. v0 delegates to `docker build` + `PullImage`.
	BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*BuildImageResponse, error)
	// Push a DAG image to an OCI-compatible registry. Walks the
	// DAG root, reconstructs OCI tar.gz layers from file blobs,
	// computes OCI digests, and uploads the config + manifest.
	PushImage(ctx context.Context, in *PushImageRequest, opts ...grpc.CallOption) (*PushImageResponse, error)
	// Export a DAG root as a tar archive. The archive contains
	// the serialized DAG nodes and their blob data, suitable for
	// backup or transfer. Streamed so large images don't require
	// a single in-memory buffer on the server.
	ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportImageChunk], error)
	// Import a tar archive previously exported via ExportImage.
	// Nodes are deduplicated against existing content in the
	// store (content-addressed). Returns the root digest and
	// storage statistics.
	ImportImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportImageChunk, ImportImageResponse], error)
	// Batch-launch multiple services from a Compose project.
	// Services are created in dependency order (depends_on).
	// On first failure, returns the error; already-started
	// workloads are NOT automatically stopped (the client
	// should call StopWorkload for rollback).
	RunCompose(ctx context.Context, in *RunComposeRequest, opts ...grpc.CallOption) (*RunComposeResponse, error)
	// Copy a file into or out of a running workload (docker cp equivalent).
	// Direction "out": reads a file from the container's rootfs and returns
	// its content. Direction "in": writes content into the container's rootfs.
	CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error)
	// Commit a running workload as a new image layer (docker commit equivalent).
	// Walks the container rootfs, creates new DAG tree/layer/manifest nodes,
	// and stores the result in the DAG store. The new image inherits the
	// original image's entrypoint, cmd, env, and working dir.
	CommitImage(ctx context.Context, in *CommitImageRequest, opts ...grpc.CallOption) (*CommitImageResponse, error)
	// Diff a running workload against its original image (docker diff equivalent).
	// Returns lists of files that were added, modified, or deleted.
	DiffWorkload(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error)
	// Return runtime info: version, uptime, store statistics, workload counts.
	RuntimeInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Create a user-defined bridge network (docker network create equivalent).
	// Creates a Linux bridge device and registers it in the runtime's network
	// registry. Workloads can attach by setting bridge_name on RunRequest.
	CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error)
	// Remove a user-defined bridge network. Deletes the Linux bridge device.
	RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error)
	// List all registered networks.
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
	// Prune removes stopped workloads, stale bundles, and temporary
	// materialized rootfs directories to reclaim disk space.
	Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error)
	// Garbage collect unreachable DAG nodes.
	Gc(ctx context.Context, in *GcRequest, opts ...grpc.CallOption) (*GcResponse, error)
	// Secret CRUD.
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	InspectSecret(ctx context.Context, in *InspectSecretRequest, opts ...grpc.CallOption) (*InspectSecretResponse, error)
	RemoveSecret(ctx context.Context, in *RemoveSecretRequest, opts ...grpc.CallOption) (*RemoveSecretResponse, error)
	// Config CRUD (identical shape to secrets, stored unencrypted).
	CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error)
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
	InspectConfig(ctx context.Context, in *InspectConfigRequest, opts ...grpc.CallOption) (*InspectConfigResponse, error)
	RemoveConfig(ctx context.Context, in *RemoveConfigRequest, opts ...grpc.CallOption) (*RemoveConfigResponse, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, Runtime_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RunWorkload(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, Runtime_RunWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StopWorkload(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Runtime_StopWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStatus)
	err := c.cc.Invoke(ctx, Runtime_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *runtimeClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[1], Runtime_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *runtimeClient) ExecInWorkload(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Runtime_ExecInWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) InspectWorkload(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, Runtime_InspectWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) AttachWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachMessage, AttachMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[2], Runtime_AttachWorkload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachMessage, AttachMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachWorkloadClient = grpc.BidiStreamingClient[AttachMessage, AttachMessage]

func (c *runtimeClient) HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasImageResponse)
	err := c.cc.Invoke(ctx, Runtime_HasImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Runtime_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DagStoreInfo(ctx context.Context, in *DagStoreInfoRequest, opts ...grpc.CallOption) (*DagStoreInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DagStoreInfoResponse)
	err := c.cc.Invoke(ctx, Runtime_DagStoreInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PortForward(ctx context.Context, in *PortForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortForwardData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[3], Runtime_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortForwardRequest, PortForwardData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardClient = grpc.ServerStreamingClient[PortForwardData]

func (c *runtimeClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkloadResponse)
	err := c.cc.Invoke(ctx, Runtime_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*WorkloadStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStats)
	err := c.cc.Invoke(ctx, Runtime_GetWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) BuildImage(ctx context.Context, in *BuildImageRequest, opts ...grpc.CallOption) (*BuildImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildImageResponse)
	err := c.cc.Invoke(ctx, Runtime_BuildImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PushImage(ctx context.Context, in *PushImageRequest, opts ...grpc.CallOption) (*PushImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushImageResponse)
	err := c.cc.Invoke(ctx, Runtime_PushImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ExportImage(ctx context.Context, in *ExportImageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportImageChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[4], Runtime_ExportImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportImageRequest, ExportImageChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ExportImageClient = grpc.ServerStreamingClient[ExportImageChunk]

func (c *runtimeClient) ImportImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportImageChunk, ImportImageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[5], Runtime_ImportImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportImageChunk, ImportImageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ImportImageClient = grpc.ClientStreamingClient[ImportImageChunk, ImportImageResponse]

func (c *runtimeClient) RunCompose(ctx context.Context, in *RunComposeRequest, opts ...grpc.CallOption) (*RunComposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunComposeResponse)
	err := c.cc.Invoke(ctx, Runtime_RunCompose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CopyFile(ctx context.Context, in *CopyFileRequest, opts ...grpc.CallOption) (*CopyFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyFileResponse)
	err := c.cc.Invoke(ctx, Runtime_CopyFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CommitImage(ctx context.Context, in *CommitImageRequest, opts ...grpc.CallOption) (*CommitImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitImageResponse)
	err := c.cc.Invoke(ctx, Runtime_CommitImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DiffWorkload(ctx context.Context, in *DiffRequest, opts ...grpc.CallOption) (*DiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffResponse)
	err := c.cc.Invoke(ctx, Runtime_DiffWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RuntimeInfo(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, Runtime_RuntimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CreateNetwork(ctx context.Context, in *CreateNetworkRequest, opts ...grpc.CallOption) (*CreateNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNetworkResponse)
	err := c.cc.Invoke(ctx, Runtime_CreateNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveNetwork(ctx context.Context, in *RemoveNetworkRequest, opts ...grpc.CallOption) (*RemoveNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNetworkResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, Runtime_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Prune(ctx context.Context, in *PruneRequest, opts ...grpc.CallOption) (*PruneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PruneResponse)
	err := c.cc.Invoke(ctx, Runtime_Prune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) Gc(ctx context.Context, in *GcRequest, opts ...grpc.CallOption) (*GcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GcResponse)
	err := c.cc.Invoke(ctx, Runtime_Gc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, Runtime_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) InspectSecret(ctx context.Context, in *InspectSecretRequest, opts ...grpc.CallOption) (*InspectSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSecretResponse)
	err := c.cc.Invoke(ctx, Runtime_InspectSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveSecret(ctx context.Context, in *RemoveSecretRequest, opts ...grpc.CallOption) (*RemoveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSecretResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*CreateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConfigResponse)
	err := c.cc.Invoke(ctx, Runtime_CreateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) InspectConfig(ctx context.Context, in *InspectConfigRequest, opts ...grpc.CallOption) (*InspectConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectConfigResponse)
	err := c.cc.Invoke(ctx, Runtime_InspectConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveConfig(ctx context.Context, in *RemoveConfigRequest, opts ...grpc.CallOption) (*RemoveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveConfigResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	RunWorkload(context.Context, *RunRequest) (*RunResponse, error)
	StopWorkload(context.Context, *StopRequest) (*StopResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*WorkloadStatus, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	ExecInWorkload(context.Context, *ExecRequest) (*ExecResponse, error)
	InspectWorkload(context.Context, *InspectRequest) (*InspectResponse, error)
	// Interactive attach to a workload's stdio. The first request
	// opens the stream; subsequent messages carry stdin/eof
	// (client -> server) and stdout/stderr/exit (server -> client).
	// Used by `pullrun workload run alpine:3.18 -- /bin/sh` and
	// similar interactive workloads on microVM backends.
	AttachWorkload(grpc.BidiStreamingServer[AttachMessage, AttachMessage]) error
	// Image management
	HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	DagStoreInfo(context.Context, *DagStoreInfoRequest) (*DagStoreInfoResponse, error)
	// Port forwarding
	PortForward(*PortForwardRequest, grpc.ServerStreamingServer[PortForwardData]) error
	// Workload resource updates
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error)
	// Workload statistics
	GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*WorkloadStats, error)
	// Build an OCI image from a Dockerfile and import into the
	// DAG store. v0 delegates to `docker build` + `PullImage`.
	BuildImage(context.Context, *BuildImageRequest) (*BuildImageResponse, error)
	// Push a DAG image to an OCI-compatible registry. Walks the
	// DAG root, reconstructs OCI tar.gz layers from file blobs,
	// computes OCI digests, and uploads the config + manifest.
	PushImage(context.Context, *PushImageRequest) (*PushImageResponse, error)
	// Export a DAG root as a tar archive. The archive contains
	// the serialized DAG nodes and their blob data, suitable for
	// backup or transfer. Streamed so large images don't require
	// a single in-memory buffer on the server.
	ExportImage(*ExportImageRequest, grpc.ServerStreamingServer[ExportImageChunk]) error
	// Import a tar archive previously exported via ExportImage.
	// Nodes are deduplicated against existing content in the
	// store (content-addressed). Returns the root digest and
	// storage statistics.
	ImportImage(grpc.ClientStreamingServer[ImportImageChunk, ImportImageResponse]) error
	// Batch-launch multiple services from a Compose project.
	// Services are created in dependency order (depends_on).
	// On first failure, returns the error; already-started
	// workloads are NOT automatically stopped (the client
	// should call StopWorkload for rollback).
	RunCompose(context.Context, *RunComposeRequest) (*RunComposeResponse, error)
	// Copy a file into or out of a running workload (docker cp equivalent).
	// Direction "out": reads a file from the container's rootfs and returns
	// its content. Direction "in": writes content into the container's rootfs.
	CopyFile(context.Context, *CopyFileRequest) (*CopyFileResponse, error)
	// Commit a running workload as a new image layer (docker commit equivalent).
	// Walks the container rootfs, creates new DAG tree/layer/manifest nodes,
	// and stores the result in the DAG store. The new image inherits the
	// original image's entrypoint, cmd, env, and working dir.
	CommitImage(context.Context, *CommitImageRequest) (*CommitImageResponse, error)
	// Diff a running workload against its original image (docker diff equivalent).
	// Returns lists of files that were added, modified, or deleted.
	DiffWorkload(context.Context, *DiffRequest) (*DiffResponse, error)
	// Return runtime info: version, uptime, store statistics, workload counts.
	RuntimeInfo(context.Context, *InfoRequest) (*InfoResponse, error)
	// Create a user-defined bridge network (docker network create equivalent).
	// Creates a Linux bridge device and registers it in the runtime's network
	// registry. Workloads can attach by setting bridge_name on RunRequest.
	CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error)
	// Remove a user-defined bridge network. Deletes the Linux bridge device.
	RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error)
	// List all registered networks.
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	// Prune removes stopped workloads, stale bundles, and temporary
	// materialized rootfs directories to reclaim disk space.
	Prune(context.Context, *PruneRequest) (*PruneResponse, error)
	// Garbage collect unreachable DAG nodes.
	Gc(context.Context, *GcRequest) (*GcResponse, error)
	// Secret CRUD.
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	InspectSecret(context.Context, *InspectSecretRequest) (*InspectSecretResponse, error)
	RemoveSecret(context.Context, *RemoveSecretRequest) (*RemoveSecretResponse, error)
	// Config CRUD (identical shape to secrets, stored unencrypted).
	CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
	InspectConfig(context.Context, *InspectConfigRequest) (*InspectConfigResponse, error)
	RemoveConfig(context.Context, *RemoveConfigRequest) (*RemoveConfigResponse, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedRuntimeServer) RunWorkload(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkload not implemented")
}
func (UnimplementedRuntimeServer) StopWorkload(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorkload not implemented")
}
func (UnimplementedRuntimeServer) GetWorkload(context.Context, *GetWorkloadRequest) (*WorkloadStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedRuntimeServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedRuntimeServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedRuntimeServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRuntimeServer) ExecInWorkload(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecInWorkload not implemented")
}
func (UnimplementedRuntimeServer) InspectWorkload(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectWorkload not implemented")
}
func (UnimplementedRuntimeServer) AttachWorkload(grpc.BidiStreamingServer[AttachMessage, AttachMessage]) error {
	return status.Error(codes.Unimplemented, "method AttachWorkload not implemented")
}
func (UnimplementedRuntimeServer) HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasImage not implemented")
}
func (UnimplementedRuntimeServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedRuntimeServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedRuntimeServer) DagStoreInfo(context.Context, *DagStoreInfoRequest) (*DagStoreInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DagStoreInfo not implemented")
}
func (UnimplementedRuntimeServer) PortForward(*PortForwardRequest, grpc.ServerStreamingServer[PortForwardData]) error {
	return status.Error(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedRuntimeServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedRuntimeServer) GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*WorkloadStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloadStats not implemented")
}
func (UnimplementedRuntimeServer) BuildImage(context.Context, *BuildImageRequest) (*BuildImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildImage not implemented")
}
func (UnimplementedRuntimeServer) PushImage(context.Context, *PushImageRequest) (*PushImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushImage not implemented")
}
func (UnimplementedRuntimeServer) ExportImage(*ExportImageRequest, grpc.ServerStreamingServer[ExportImageChunk]) error {
	return status.Error(codes.Unimplemented, "method ExportImage not implemented")
}
func (UnimplementedRuntimeServer) ImportImage(grpc.ClientStreamingServer[ImportImageChunk, ImportImageResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportImage not implemented")
}
func (UnimplementedRuntimeServer) RunCompose(context.Context, *RunComposeRequest) (*RunComposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCompose not implemented")
}
func (UnimplementedRuntimeServer) CopyFile(context.Context, *CopyFileRequest) (*CopyFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFile not implemented")
}
func (UnimplementedRuntimeServer) CommitImage(context.Context, *CommitImageRequest) (*CommitImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitImage not implemented")
}
func (UnimplementedRuntimeServer) DiffWorkload(context.Context, *DiffRequest) (*DiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffWorkload not implemented")
}
func (UnimplementedRuntimeServer) RuntimeInfo(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RuntimeInfo not implemented")
}
func (UnimplementedRuntimeServer) CreateNetwork(context.Context, *CreateNetworkRequest) (*CreateNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNetwork not implemented")
}
func (UnimplementedRuntimeServer) RemoveNetwork(context.Context, *RemoveNetworkRequest) (*RemoveNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNetwork not implemented")
}
func (UnimplementedRuntimeServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedRuntimeServer) Prune(context.Context, *PruneRequest) (*PruneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prune not implemented")
}
func (UnimplementedRuntimeServer) Gc(context.Context, *GcRequest) (*GcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Gc not implemented")
}
func (UnimplementedRuntimeServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedRuntimeServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedRuntimeServer) InspectSecret(context.Context, *InspectSecretRequest) (*InspectSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSecret not implemented")
}
func (UnimplementedRuntimeServer) RemoveSecret(context.Context, *RemoveSecretRequest) (*RemoveSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSecret not implemented")
}
func (UnimplementedRuntimeServer) CreateConfig(context.Context, *CreateConfigRequest) (*CreateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConfig not implemented")
}
func (UnimplementedRuntimeServer) ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigs not implemented")
}
func (UnimplementedRuntimeServer) InspectConfig(context.Context, *InspectConfigRequest) (*InspectConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectConfig not implemented")
}
func (UnimplementedRuntimeServer) RemoveConfig(context.Context, *RemoveConfigRequest) (*RemoveConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveConfig not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RunWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RunWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RunWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RunWorkload(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StopWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StopWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StopWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StopWorkload(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

func _Runtime_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _Runtime_ExecInWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ExecInWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ExecInWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ExecInWorkload(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_InspectWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).InspectWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_InspectWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).InspectWorkload(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_AttachWorkload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).AttachWorkload(&grpc.GenericServerStream[AttachMessage, AttachMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachWorkloadServer = grpc.BidiStreamingServer[AttachMessage, AttachMessage]

func _Runtime_HasImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).HasImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_HasImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).HasImage(ctx, req.(*HasImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DagStoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DagStoreInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DagStoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DagStoreInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DagStoreInfo(ctx, req.(*DagStoreInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PortForwardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).PortForward(m, &grpc.GenericServerStream[PortForwardRequest, PortForwardData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardServer = grpc.ServerStreamingServer[PortForwardData]

func _Runtime_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetWorkloadStats(ctx, req.(*GetWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_BuildImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).BuildImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_BuildImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).BuildImage(ctx, req.(*BuildImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PushImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PushImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PushImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PushImage(ctx, req.(*PushImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ExportImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportImageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).ExportImage(m, &grpc.GenericServerStream[ExportImageRequest, ExportImageChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ExportImageServer = grpc.ServerStreamingServer[ExportImageChunk]

func _Runtime_ImportImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).ImportImage(&grpc.GenericServerStream[ImportImageChunk, ImportImageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_ImportImageServer = grpc.ClientStreamingServer[ImportImageChunk, ImportImageResponse]

func _Runtime_RunCompose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunComposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RunCompose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RunCompose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RunCompose(ctx, req.(*RunComposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CopyFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CopyFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CopyFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CopyFile(ctx, req.(*CopyFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CommitImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CommitImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CommitImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CommitImage(ctx, req.(*CommitImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DiffWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DiffWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DiffWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DiffWorkload(ctx, req.(*DiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RuntimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RuntimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RuntimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RuntimeInfo(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CreateNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CreateNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CreateNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CreateNetwork(ctx, req.(*CreateNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveNetwork(ctx, req.(*RemoveNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Prune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Prune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Prune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Prune(ctx, req.(*PruneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_Gc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).Gc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_Gc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).Gc(ctx, req.(*GcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_InspectSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).InspectSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_InspectSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).InspectSecret(ctx, req.(*InspectSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveSecret(ctx, req.(*RemoveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_CreateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).CreateConfig(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_InspectConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).InspectConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_InspectConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).InspectConfig(ctx, req.(*InspectConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveConfig(ctx, req.(*RemoveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pullrun.runtime.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullImage",
			Handler:    _Runtime_PullImage_Handler,
		},
		{
			MethodName: "RunWorkload",
			Handler:    _Runtime_RunWorkload_Handler,
		},
		{
			MethodName: "StopWorkload",
			Handler:    _Runtime_StopWorkload_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _Runtime_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _Runtime_ListWorkloads_Handler,
		},
		{
			MethodName: "ExecInWorkload",
			Handler:    _Runtime_ExecInWorkload_Handler,
		},
		{
			MethodName: "InspectWorkload",
			Handler:    _Runtime_InspectWorkload_Handler,
		},
		{
			MethodName: "HasImage",
			Handler:    _Runtime_HasImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _Runtime_ListImages_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _Runtime_RemoveImage_Handler,
		},
		{
			MethodName: "DagStoreInfo",
			Handler:    _Runtime_DagStoreInfo_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _Runtime_UpdateWorkload_Handler,
		},
		{
			MethodName: "GetWorkloadStats",
			Handler:    _Runtime_GetWorkloadStats_Handler,
		},
		{
			MethodName: "BuildImage",
			Handler:    _Runtime_BuildImage_Handler,
		},
		{
			MethodName: "PushImage",
			Handler:    _Runtime_PushImage_Handler,
		},
		{
			MethodName: "RunCompose",
			Handler:    _Runtime_RunCompose_Handler,
		},
		{
			MethodName: "CopyFile",
			Handler:    _Runtime_CopyFile_Handler,
		},
		{
			MethodName: "CommitImage",
			Handler:    _Runtime_CommitImage_Handler,
		},
		{
			MethodName: "DiffWorkload",
			Handler:    _Runtime_DiffWorkload_Handler,
		},
		{
			MethodName: "RuntimeInfo",
			Handler:    _Runtime_RuntimeInfo_Handler,
		},
		{
			MethodName: "CreateNetwork",
			Handler:    _Runtime_CreateNetwork_Handler,
		},
		{
			MethodName: "RemoveNetwork",
			Handler:    _Runtime_RemoveNetwork_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _Runtime_ListNetworks_Handler,
		},
		{
			MethodName: "Prune",
			Handler:    _Runtime_Prune_Handler,
		},
		{
			MethodName: "Gc",
			Handler:    _Runtime_Gc_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _Runtime_CreateSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _Runtime_ListSecrets_Handler,
		},
		{
			MethodName: "InspectSecret",
			Handler:    _Runtime_InspectSecret_Handler,
		},
		{
			MethodName: "RemoveSecret",
			Handler:    _Runtime_RemoveSecret_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _Runtime_CreateConfig_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _Runtime_ListConfigs_Handler,
		},
		{
			MethodName: "InspectConfig",
			Handler:    _Runtime_InspectConfig_Handler,
		},
		{
			MethodName: "RemoveConfig",
			Handler:    _Runtime_RemoveConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Runtime_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Runtime_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AttachWorkload",
			Handler:       _Runtime_AttachWorkload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _Runtime_PortForward_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExportImage",
			Handler:       _Runtime_ExportImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportImage",
			Handler:       _Runtime_ImportImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pullrun/runtime.proto",
}
