// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nimbus/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	runtime "nimbus/protoapi/nimbus/runtime"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageRef      string                 `protobuf:"bytes,2,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Resources     *Resources             `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	NetworkRules  []*runtime.NetworkRule `protobuf:"bytes,5,rep,name=network_rules,json=networkRules,proto3" json:"network_rules,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_nimbus_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkloadSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadSpec) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *WorkloadSpec) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *WorkloadSpec) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkloadSpec) GetNetworkRules() []*runtime.NetworkRule {
	if x != nil {
		return x.NetworkRules
	}
	return nil
}

func (x *WorkloadSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores uint64                 `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_nimbus_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetCpuMillicores() uint64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *Resources) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_nimbus_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelFilter   map[string]string      `protobuf:"bytes,1,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_nimbus_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

type WorkloadList struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*runtime.WorkloadStatus `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadList) Reset() {
	*x = WorkloadList{}
	mi := &file_nimbus_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadList) ProtoMessage() {}

func (x *WorkloadList) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadList.ProtoReflect.Descriptor instead.
func (*WorkloadList) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadList) GetItems() []*runtime.WorkloadStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_nimbus_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_nimbus_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_nimbus_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{7}
}

type NodeRegistration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CpuCores          uint64                 `protobuf:"varint,3,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryBytes       uint64                 `protobuf:"varint,4,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	HostPlatform      string                 `protobuf:"bytes,5,opt,name=host_platform,json=hostPlatform,proto3" json:"host_platform,omitempty"`
	AvailableBackends []string               `protobuf:"bytes,6,rep,name=available_backends,json=availableBackends,proto3" json:"available_backends,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeRegistration) Reset() {
	*x = NodeRegistration{}
	mi := &file_nimbus_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistration) ProtoMessage() {}

func (x *NodeRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistration.ProtoReflect.Descriptor instead.
func (*NodeRegistration) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{8}
}

func (x *NodeRegistration) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeRegistration) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeRegistration) GetCpuCores() uint64 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeRegistration) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *NodeRegistration) GetHostPlatform() string {
	if x != nil {
		return x.HostPlatform
	}
	return ""
}

func (x *NodeRegistration) GetAvailableBackends() []string {
	if x != nil {
		return x.AvailableBackends
	}
	return nil
}

type RegisterResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AssignedId          string                 `protobuf:"bytes,1,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_nimbus_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type HeartbeatRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RunningWorkloads       uint64                 `protobuf:"varint,2,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`
	AvailableCpuMillicores uint64                 `protobuf:"varint,3,opt,name=available_cpu_millicores,json=availableCpuMillicores,proto3" json:"available_cpu_millicores,omitempty"`
	AvailableMemoryBytes   uint64                 `protobuf:"varint,4,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_nimbus_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningWorkloads() uint64 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableCpuMillicores() uint64 {
	if x != nil {
		return x.AvailableCpuMillicores
	}
	return 0
}

func (x *HeartbeatRequest) GetAvailableMemoryBytes() uint64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

type HeartbeatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PendingWorkloads []*WorkloadSpec        `protobuf:"bytes,2,rep,name=pending_workloads,json=pendingWorkloads,proto3" json:"pending_workloads,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_nimbus_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_control_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetPendingWorkloads() []*WorkloadSpec {
	if x != nil {
		return x.PendingWorkloads
	}
	return nil
}

var File_nimbus_control_proto protoreflect.FileDescriptor

const file_nimbus_control_proto_rawDesc = "" +
	"\n" +
	"\x14nimbus/control.proto\x12\x0enimbus.control\x1a\x14nimbus/runtime.proto\"\xd1\x02\n" +
	"\fWorkloadSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_ref\x18\x02 \x01(\tR\bimageRef\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x127\n" +
	"\tresources\x18\x04 \x01(\v2\x19.nimbus.control.ResourcesR\tresources\x12@\n" +
	"\rnetwork_rules\x18\x05 \x03(\v2\x1b.nimbus.runtime.NetworkRuleR\fnetworkRules\x12@\n" +
	"\x06labels\x18\x06 \x03(\v2(.nimbus.control.WorkloadSpec.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\tResources\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x04R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"\x1c\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9e\x01\n" +
	"\vListRequest\x12O\n" +
	"\flabel_filter\x18\x01 \x03(\v2,.nimbus.control.ListRequest.LabelFilterEntryR\vlabelFilter\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\fWorkloadList\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.nimbus.runtime.WorkloadStatusR\x05items\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\"\xd9\x01\n" +
	"\x10NodeRegistration\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1b\n" +
	"\tcpu_cores\x18\x03 \x01(\x04R\bcpuCores\x12!\n" +
	"\fmemory_bytes\x18\x04 \x01(\x04R\vmemoryBytes\x12#\n" +
	"\rhost_platform\x18\x05 \x01(\tR\fhostPlatform\x12-\n" +
	"\x12available_backends\x18\x06 \x03(\tR\x11availableBackends\"g\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vassigned_id\x18\x01 \x01(\tR\n" +
	"assignedId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\"\xc8\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12+\n" +
	"\x11running_workloads\x18\x02 \x01(\x04R\x10runningWorkloads\x128\n" +
	"\x18available_cpu_millicores\x18\x03 \x01(\x04R\x16availableCpuMillicores\x124\n" +
	"\x16available_memory_bytes\x18\x04 \x01(\x04R\x14availableMemoryBytes\"n\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12I\n" +
	"\x11pending_workloads\x18\x02 \x03(\v2\x1c.nimbus.control.WorkloadSpecR\x10pendingWorkloads2\xac\x04\n" +
	"\fControlPlane\x12N\n" +
	"\x0eSubmitWorkload\x12\x1c.nimbus.control.WorkloadSpec\x1a\x1e.nimbus.runtime.WorkloadStatus\x12I\n" +
	"\vGetWorkload\x12\x1a.nimbus.control.GetRequest\x1a\x1e.nimbus.runtime.WorkloadStatus\x12J\n" +
	"\rListWorkloads\x12\x1b.nimbus.control.ListRequest\x1a\x1c.nimbus.control.WorkloadList\x12O\n" +
	"\x0eDeleteWorkload\x12\x1d.nimbus.control.DeleteRequest\x1a\x1e.nimbus.control.DeleteResponse\x12>\n" +
	"\fStreamEvents\x12\x15.nimbus.control.Empty\x1a\x15.nimbus.runtime.Event0\x01\x12R\n" +
	"\fRegisterNode\x12 .nimbus.control.NodeRegistration\x1a .nimbus.control.RegisterResponse\x12P\n" +
	"\tHeartbeat\x12 .nimbus.control.HeartbeatRequest\x1a!.nimbus.control.HeartbeatResponseB(Z&nimbus/protoapi/nimbus/control;controlb\x06proto3"

var (
	file_nimbus_control_proto_rawDescOnce sync.Once
	file_nimbus_control_proto_rawDescData []byte
)

func file_nimbus_control_proto_rawDescGZIP() []byte {
	file_nimbus_control_proto_rawDescOnce.Do(func() {
		file_nimbus_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nimbus_control_proto_rawDesc), len(file_nimbus_control_proto_rawDesc)))
	})
	return file_nimbus_control_proto_rawDescData
}

var file_nimbus_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_nimbus_control_proto_goTypes = []any{
	(*WorkloadSpec)(nil),           // 0: nimbus.control.WorkloadSpec
	(*Resources)(nil),              // 1: nimbus.control.Resources
	(*GetRequest)(nil),             // 2: nimbus.control.GetRequest
	(*ListRequest)(nil),            // 3: nimbus.control.ListRequest
	(*WorkloadList)(nil),           // 4: nimbus.control.WorkloadList
	(*DeleteRequest)(nil),          // 5: nimbus.control.DeleteRequest
	(*DeleteResponse)(nil),         // 6: nimbus.control.DeleteResponse
	(*Empty)(nil),                  // 7: nimbus.control.Empty
	(*NodeRegistration)(nil),       // 8: nimbus.control.NodeRegistration
	(*RegisterResponse)(nil),       // 9: nimbus.control.RegisterResponse
	(*HeartbeatRequest)(nil),       // 10: nimbus.control.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 11: nimbus.control.HeartbeatResponse
	nil,                            // 12: nimbus.control.WorkloadSpec.LabelsEntry
	nil,                            // 13: nimbus.control.ListRequest.LabelFilterEntry
	(*runtime.NetworkRule)(nil),    // 14: nimbus.runtime.NetworkRule
	(*runtime.WorkloadStatus)(nil), // 15: nimbus.runtime.WorkloadStatus
	(*runtime.Event)(nil),          // 16: nimbus.runtime.Event
}
var file_nimbus_control_proto_depIdxs = []int32{
	1,  // 0: nimbus.control.WorkloadSpec.resources:type_name -> nimbus.control.Resources
	14, // 1: nimbus.control.WorkloadSpec.network_rules:type_name -> nimbus.runtime.NetworkRule
	12, // 2: nimbus.control.WorkloadSpec.labels:type_name -> nimbus.control.WorkloadSpec.LabelsEntry
	13, // 3: nimbus.control.ListRequest.label_filter:type_name -> nimbus.control.ListRequest.LabelFilterEntry
	15, // 4: nimbus.control.WorkloadList.items:type_name -> nimbus.runtime.WorkloadStatus
	0,  // 5: nimbus.control.HeartbeatResponse.pending_workloads:type_name -> nimbus.control.WorkloadSpec
	0,  // 6: nimbus.control.ControlPlane.SubmitWorkload:input_type -> nimbus.control.WorkloadSpec
	2,  // 7: nimbus.control.ControlPlane.GetWorkload:input_type -> nimbus.control.GetRequest
	3,  // 8: nimbus.control.ControlPlane.ListWorkloads:input_type -> nimbus.control.ListRequest
	5,  // 9: nimbus.control.ControlPlane.DeleteWorkload:input_type -> nimbus.control.DeleteRequest
	7,  // 10: nimbus.control.ControlPlane.StreamEvents:input_type -> nimbus.control.Empty
	8,  // 11: nimbus.control.ControlPlane.RegisterNode:input_type -> nimbus.control.NodeRegistration
	10, // 12: nimbus.control.ControlPlane.Heartbeat:input_type -> nimbus.control.HeartbeatRequest
	15, // 13: nimbus.control.ControlPlane.SubmitWorkload:output_type -> nimbus.runtime.WorkloadStatus
	15, // 14: nimbus.control.ControlPlane.GetWorkload:output_type -> nimbus.runtime.WorkloadStatus
	4,  // 15: nimbus.control.ControlPlane.ListWorkloads:output_type -> nimbus.control.WorkloadList
	6,  // 16: nimbus.control.ControlPlane.DeleteWorkload:output_type -> nimbus.control.DeleteResponse
	16, // 17: nimbus.control.ControlPlane.StreamEvents:output_type -> nimbus.runtime.Event
	9,  // 18: nimbus.control.ControlPlane.RegisterNode:output_type -> nimbus.control.RegisterResponse
	11, // 19: nimbus.control.ControlPlane.Heartbeat:output_type -> nimbus.control.HeartbeatResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nimbus_control_proto_init() }
func file_nimbus_control_proto_init() {
	if File_nimbus_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nimbus_control_proto_rawDesc), len(file_nimbus_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nimbus_control_proto_goTypes,
		DependencyIndexes: file_nimbus_control_proto_depIdxs,
		MessageInfos:      file_nimbus_control_proto_msgTypes,
	}.Build()
	File_nimbus_control_proto = out.File
	file_nimbus_control_proto_goTypes = nil
	file_nimbus_control_proto_depIdxs = nil
}
