// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nimbus/runtime.proto

package runtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	Registry      string                 `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImageRequest) Reset() {
	*x = PullImageRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageRequest) ProtoMessage() {}

func (x *PullImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageRequest.ProtoReflect.Descriptor instead.
func (*PullImageRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *PullImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *PullImageRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

type PullImageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RootDigest        string                 `protobuf:"bytes,1,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	BytesStored       int64                  `protobuf:"varint,2,opt,name=bytes_stored,json=bytesStored,proto3" json:"bytes_stored,omitempty"`
	BytesDeduplicated int64                  `protobuf:"varint,3,opt,name=bytes_deduplicated,json=bytesDeduplicated,proto3" json:"bytes_deduplicated,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PullImageResponse) Reset() {
	*x = PullImageResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImageResponse) ProtoMessage() {}

func (x *PullImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImageResponse.ProtoReflect.Descriptor instead.
func (*PullImageResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *PullImageResponse) GetRootDigest() string {
	if x != nil {
		return x.RootDigest
	}
	return ""
}

func (x *PullImageResponse) GetBytesStored() int64 {
	if x != nil {
		return x.BytesStored
	}
	return 0
}

func (x *PullImageResponse) GetBytesDeduplicated() int64 {
	if x != nil {
		return x.BytesDeduplicated
	}
	return 0
}

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RootDigest    string                 `protobuf:"bytes,2,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	Backend       string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Command       []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CpuMillicores uint64                 `protobuf:"varint,6,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,7,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	NetworkMode   string                 `protobuf:"bytes,8,opt,name=network_mode,json=networkMode,proto3" json:"network_mode,omitempty"`
	NetworkRules  []*NetworkRule         `protobuf:"bytes,9,rep,name=network_rules,json=networkRules,proto3" json:"network_rules,omitempty"`
	// OCI image ref for the kernel. Required when
	// backend="vm". The runtime stages the kernel via the
	// standard OCI pipeline and stores it in an in-memory
	// kernel cache so the subsequent AttachWorkload RPC
	// can boot the same VM.
	//
	// Format: "registry/repo:tag" (e.g.
	// "nimbus/kernel-asahi:6.19.14" or
	// "ghcr.io/nimbus/kernel:6.19.14"). The image MUST
	// have the label "org.nimbus.image.kind=kernel" and
	// contain /boot/vmlinux (and optionally
	// /boot/initramfs.cpio.gz).
	KernelImage string `protobuf:"bytes,10,opt,name=kernel_image,json=kernelImage,proto3" json:"kernel_image,omitempty"`
	// Working directory inside the workload. Defaults to
	// "/" if empty. The guest's nimbus-init changes to
	// this directory before exec'ing the command.
	WorkingDir    string `protobuf:"bytes,11,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *RunRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunRequest) GetRootDigest() string {
	if x != nil {
		return x.RootDigest
	}
	return ""
}

func (x *RunRequest) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *RunRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetCpuMillicores() uint64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *RunRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RunRequest) GetNetworkMode() string {
	if x != nil {
		return x.NetworkMode
	}
	return ""
}

func (x *RunRequest) GetNetworkRules() []*NetworkRule {
	if x != nil {
		return x.NetworkRules
	}
	return nil
}

func (x *RunRequest) GetKernelImage() string {
	if x != nil {
		return x.KernelImage
	}
	return ""
}

func (x *RunRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type NetworkRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	ToHost        string                 `protobuf:"bytes,4,opt,name=to_host,json=toHost,proto3" json:"to_host,omitempty"`
	FromCidrs     []string               `protobuf:"bytes,5,rep,name=from_cidrs,json=fromCidrs,proto3" json:"from_cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRule) Reset() {
	*x = NetworkRule{}
	mi := &file_nimbus_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRule) ProtoMessage() {}

func (x *NetworkRule) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRule.ProtoReflect.Descriptor instead.
func (*NetworkRule) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkRule) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *NetworkRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkRule) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkRule) GetToHost() string {
	if x != nil {
		return x.ToHost
	}
	return ""
}

func (x *NetworkRule) GetFromCidrs() []string {
	if x != nil {
		return x.FromCidrs
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	BackendUsed   string                 `protobuf:"bytes,3,opt,name=backend_used,json=backendUsed,proto3" json:"backend_used,omitempty"`
	InternalIp    string                 `protobuf:"bytes,4,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *RunResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RunResponse) GetBackendUsed() string {
	if x != nil {
		return x.BackendUsed
	}
	return ""
}

func (x *RunResponse) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *StopRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *StopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *GetWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkloadStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Backend         string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	ExitCode        uint32                 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StartTime       int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	InternalIp      string                 `protobuf:"bytes,6,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	NetworkIsolated bool                   `protobuf:"varint,7,opt,name=network_isolated,json=networkIsolated,proto3" json:"network_isolated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_nimbus_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *WorkloadStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkloadStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WorkloadStatus) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *WorkloadStatus) GetExitCode() uint32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkloadStatus) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *WorkloadStatus) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *WorkloadStatus) GetNetworkIsolated() bool {
	if x != nil {
		return x.NetworkIsolated
	}
	return false
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{9}
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadStatus      `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*WorkloadStatus {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	Tail          int64                  `protobuf:"varint,3,opt,name=tail,proto3" json:"tail,omitempty"`
	Since         int64                  `protobuf:"varint,4,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *StreamLogsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamLogsRequest) GetTail() int64 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *StreamLogsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Stderr        bool                   `protobuf:"varint,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_nimbus_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

func (x *LogChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *StreamEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_nimbus_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *ExecRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

// One message in the bidirectional AttachWorkload stream. The
// first message from the client MUST be AttachOpen. After that,
// the client may send AttachStdin/AttachStdinEof, and the server
// will send AttachStdout/AttachStderr/AttachExit.
//
// This is the gRPC projection of the in-VM vsock protocol
// (see runtime/nimbus-vsock/src/lib.rs). The wire shape is
// identical except that one stream of bytes is split into
// repeated bytes messages, which is what gRPC wants.
type AttachMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one of these is set per message.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*AttachMessage_Open
	//	*AttachMessage_Stdin
	//	*AttachMessage_StdinEof
	//	*AttachMessage_Stdout
	//	*AttachMessage_Stderr
	//	*AttachMessage_Exit
	//	*AttachMessage_Error
	Body          isAttachMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachMessage) Reset() {
	*x = AttachMessage{}
	mi := &file_nimbus_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachMessage) ProtoMessage() {}

func (x *AttachMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachMessage.ProtoReflect.Descriptor instead.
func (*AttachMessage) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *AttachMessage) GetBody() isAttachMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AttachMessage) GetOpen() *AttachOpen {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *AttachMessage) GetStdin() *AttachStdin {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *AttachMessage) GetStdinEof() *AttachStdinEof {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_StdinEof); ok {
			return x.StdinEof
		}
	}
	return nil
}

func (x *AttachMessage) GetStdout() *AttachStdout {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *AttachMessage) GetStderr() *AttachStderr {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *AttachMessage) GetExit() *AttachExit {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *AttachMessage) GetError() *AttachError {
	if x != nil {
		if x, ok := x.Body.(*AttachMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAttachMessage_Body interface {
	isAttachMessage_Body()
}

type AttachMessage_Open struct {
	Open *AttachOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type AttachMessage_Stdin struct {
	Stdin *AttachStdin `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type AttachMessage_StdinEof struct {
	StdinEof *AttachStdinEof `protobuf:"bytes,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

type AttachMessage_Stdout struct {
	Stdout *AttachStdout `protobuf:"bytes,4,opt,name=stdout,proto3,oneof"`
}

type AttachMessage_Stderr struct {
	Stderr *AttachStderr `protobuf:"bytes,5,opt,name=stderr,proto3,oneof"`
}

type AttachMessage_Exit struct {
	Exit *AttachExit `protobuf:"bytes,6,opt,name=exit,proto3,oneof"`
}

type AttachMessage_Error struct {
	Error *AttachError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*AttachMessage_Open) isAttachMessage_Body() {}

func (*AttachMessage_Stdin) isAttachMessage_Body() {}

func (*AttachMessage_StdinEof) isAttachMessage_Body() {}

func (*AttachMessage_Stdout) isAttachMessage_Body() {}

func (*AttachMessage_Stderr) isAttachMessage_Body() {}

func (*AttachMessage_Exit) isAttachMessage_Body() {}

func (*AttachMessage_Error) isAttachMessage_Body() {}

// Open the stream. Tells the runtime which workload to attach to
// and what command to run (overrides the workload's default
// command, if any). Sent exactly once, as the first message.
type AttachOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachOpen) Reset() {
	*x = AttachOpen{}
	mi := &file_nimbus_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachOpen) ProtoMessage() {}

func (x *AttachOpen) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachOpen.ProtoReflect.Descriptor instead.
func (*AttachOpen) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *AttachOpen) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *AttachOpen) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AttachOpen) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *AttachOpen) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

// Bytes to feed into the workload's stdin.
type AttachStdin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStdin) Reset() {
	*x = AttachStdin{}
	mi := &file_nimbus_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStdin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStdin) ProtoMessage() {}

func (x *AttachStdin) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStdin.ProtoReflect.Descriptor instead.
func (*AttachStdin) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *AttachStdin) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Signals that no more stdin will arrive. The runtime will close
// the workload's stdin pipe and the workload will see EOF.
type AttachStdinEof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStdinEof) Reset() {
	*x = AttachStdinEof{}
	mi := &file_nimbus_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStdinEof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStdinEof) ProtoMessage() {}

func (x *AttachStdinEof) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStdinEof.ProtoReflect.Descriptor instead.
func (*AttachStdinEof) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{20}
}

// Bytes from the workload's stdout.
type AttachStdout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStdout) Reset() {
	*x = AttachStdout{}
	mi := &file_nimbus_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStdout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStdout) ProtoMessage() {}

func (x *AttachStdout) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStdout.ProtoReflect.Descriptor instead.
func (*AttachStdout) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *AttachStdout) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Bytes from the workload's stderr.
type AttachStderr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachStderr) Reset() {
	*x = AttachStderr{}
	mi := &file_nimbus_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachStderr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachStderr) ProtoMessage() {}

func (x *AttachStderr) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachStderr.ProtoReflect.Descriptor instead.
func (*AttachStderr) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{22}
}

func (x *AttachStderr) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The workload exited.
type AttachExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // 0 if exited normally with code 0
	Signal        int32                  `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`                     // 0 if not killed by signal
	HasExitCode   bool                   `protobuf:"varint,3,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	HasSignal     bool                   `protobuf:"varint,4,opt,name=has_signal,json=hasSignal,proto3" json:"has_signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachExit) Reset() {
	*x = AttachExit{}
	mi := &file_nimbus_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachExit) ProtoMessage() {}

func (x *AttachExit) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachExit.ProtoReflect.Descriptor instead.
func (*AttachExit) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *AttachExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AttachExit) GetSignal() int32 {
	if x != nil {
		return x.Signal
	}
	return 0
}

func (x *AttachExit) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *AttachExit) GetHasSignal() bool {
	if x != nil {
		return x.HasSignal
	}
	return false
}

// Hard error from the runtime (e.g. "VM died", "workload not
// found", "policy denied"). The stream is terminated after this.
type AttachError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachError) Reset() {
	*x = AttachError{}
	mi := &file_nimbus_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachError) ProtoMessage() {}

func (x *AttachError) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachError.ProtoReflect.Descriptor instead.
func (*AttachError) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *AttachError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HasImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"` // e.g. "alpine:latest" or "sha256:<digest>"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasImageRequest) Reset() {
	*x = HasImageRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasImageRequest) ProtoMessage() {}

func (x *HasImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasImageRequest.ProtoReflect.Descriptor instead.
func (*HasImageRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *HasImageRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

type HasImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	RootDigest    string                 `protobuf:"bytes,2,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasImageResponse) Reset() {
	*x = HasImageResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasImageResponse) ProtoMessage() {}

func (x *HasImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasImageResponse.ProtoReflect.Descriptor instead.
func (*HasImageResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *HasImageResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *HasImageResponse) GetRootDigest() string {
	if x != nil {
		return x.RootDigest
	}
	return ""
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{27}
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*ImageInfo           `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{28}
}

func (x *ListImagesResponse) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageRef      string                 `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	RootDigest    string                 `protobuf:"bytes,2,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_nimbus_runtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{29}
}

func (x *ImageInfo) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *ImageInfo) GetRootDigest() string {
	if x != nil {
		return x.RootDigest
	}
	return ""
}

func (x *ImageInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RemoveImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootDigest    string                 `protobuf:"bytes,1,opt,name=root_digest,json=rootDigest,proto3" json:"root_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageRequest) Reset() {
	*x = RemoveImageRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageRequest) ProtoMessage() {}

func (x *RemoveImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageRequest.ProtoReflect.Descriptor instead.
func (*RemoveImageRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveImageRequest) GetRootDigest() string {
	if x != nil {
		return x.RootDigest
	}
	return ""
}

type RemoveImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BytesFreed    int64                  `protobuf:"varint,2,opt,name=bytes_freed,json=bytesFreed,proto3" json:"bytes_freed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveImageResponse) Reset() {
	*x = RemoveImageResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveImageResponse) ProtoMessage() {}

func (x *RemoveImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveImageResponse.ProtoReflect.Descriptor instead.
func (*RemoveImageResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveImageResponse) GetBytesFreed() int64 {
	if x != nil {
		return x.BytesFreed
	}
	return 0
}

type DagStoreInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagStoreInfoRequest) Reset() {
	*x = DagStoreInfoRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagStoreInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagStoreInfoRequest) ProtoMessage() {}

func (x *DagStoreInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagStoreInfoRequest.ProtoReflect.Descriptor instead.
func (*DagStoreInfoRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{32}
}

type DagStoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mountpoint    string                 `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	TotalNodes    int64                  `protobuf:"varint,3,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`    // approximate; best-effort
	InodesUsed    int64                  `protobuf:"varint,5,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"` // approximate; best-effort
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagStoreInfoResponse) Reset() {
	*x = DagStoreInfoResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagStoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagStoreInfoResponse) ProtoMessage() {}

func (x *DagStoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagStoreInfoResponse.ProtoReflect.Descriptor instead.
func (*DagStoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{33}
}

func (x *DagStoreInfoResponse) GetMountpoint() string {
	if x != nil {
		return x.Mountpoint
	}
	return ""
}

func (x *DagStoreInfoResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DagStoreInfoResponse) GetTotalNodes() int64 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *DagStoreInfoResponse) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DagStoreInfoResponse) GetInodesUsed() int64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

type PortForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // "tcp" or "udp"
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRequest) Reset() {
	*x = PortForwardRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRequest) ProtoMessage() {}

func (x *PortForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRequest.ProtoReflect.Descriptor instead.
func (*PortForwardRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{34}
}

func (x *PortForwardRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *PortForwardRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortForwardRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PortForwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardData) Reset() {
	*x = PortForwardData{}
	mi := &file_nimbus_runtime_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardData) ProtoMessage() {}

func (x *PortForwardData) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardData.ProtoReflect.Descriptor instead.
func (*PortForwardData) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{35}
}

func (x *PortForwardData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CpuMillicores uint64                 `protobuf:"varint,2,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkloadRequest) Reset() {
	*x = UpdateWorkloadRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkloadRequest) ProtoMessage() {}

func (x *UpdateWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkloadRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkloadRequest) GetCpuMillicores() uint64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *UpdateWorkloadRequest) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type UpdateWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkloadResponse) Reset() {
	*x = UpdateWorkloadResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkloadResponse) ProtoMessage() {}

func (x *UpdateWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkloadResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{37}
}

func (x *UpdateWorkloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetWorkloadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatsRequest) Reset() {
	*x = GetWorkloadStatsRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatsRequest) ProtoMessage() {}

func (x *GetWorkloadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatsRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{38}
}

func (x *GetWorkloadStatsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WorkloadStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CpuUsagePercent float64                `protobuf:"fixed64,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryBytes     uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes       uint64                 `protobuf:"varint,4,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	NetworkRxBytes  uint64                 `protobuf:"varint,5,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkTxBytes  uint64                 `protobuf:"varint,6,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkloadStats) Reset() {
	*x = WorkloadStats{}
	mi := &file_nimbus_runtime_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStats) ProtoMessage() {}

func (x *WorkloadStats) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStats.ProtoReflect.Descriptor instead.
func (*WorkloadStats) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{39}
}

func (x *WorkloadStats) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkloadStats) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *WorkloadStats) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *WorkloadStats) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *WorkloadStats) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *WorkloadStats) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

// Deep inspection of a workload. The DAG path is the ordered list of
// `digest:kind` nodes from the root manifest down to the leaf blobs,
// so operators can see the image's exact composition at a glance.
type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_nimbus_runtime_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{40}
}

func (x *InspectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DagNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                             // "manifest" | "tree" | "layer" | "blob"
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // best-effort; 0 if unknown
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagNode) Reset() {
	*x = DagNode{}
	mi := &file_nimbus_runtime_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagNode) ProtoMessage() {}

func (x *DagNode) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagNode.ProtoReflect.Descriptor instead.
func (*DagNode) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{41}
}

func (x *DagNode) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *DagNode) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DagNode) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type InspectResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State        string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "running" | "stopped" | "exited" | "failed"
	Backend      string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	ImageRoot    string                 `protobuf:"bytes,4,opt,name=image_root,json=imageRoot,proto3" json:"image_root,omitempty"`
	InternalIp   string                 `protobuf:"bytes,5,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	Pid          uint32                 `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	StartTime    int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // unix seconds
	ExitTime     int64                  `protobuf:"varint,8,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`    // unix seconds; 0 if still running
	ExitCode     uint32                 `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`    // 0 if still running
	Command      []string               `protobuf:"bytes,10,rep,name=command,proto3" json:"command,omitempty"`
	NetworkRules []*NetworkRule         `protobuf:"bytes,11,rep,name=network_rules,json=networkRules,proto3" json:"network_rules,omitempty"`
	// DAG traversal: ordered list of `digest:kind` from root manifest
	// down to the leaf blobs. BFS, so the manifest is always first.
	DagPath []*DagNode `protobuf:"bytes,12,rep,name=dag_path,json=dagPath,proto3" json:"dag_path,omitempty"`
	// Per-policy decision log: rule -> "allow" | "deny: <reason>".
	// Populated at pull and at run time. v0 only writes a single
	// entry per decision.
	PolicyDecisions map[string]string `protobuf:"bytes,13,rep,name=policy_decisions,json=policyDecisions,proto3" json:"policy_decisions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether the workload is currently in the runtime's view of
	// the workloads map. False iff the workload has been GC'd.
	Found         bool `protobuf:"varint,14,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_nimbus_runtime_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nimbus_runtime_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_nimbus_runtime_proto_rawDescGZIP(), []int{42}
}

func (x *InspectResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InspectResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InspectResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *InspectResponse) GetImageRoot() string {
	if x != nil {
		return x.ImageRoot
	}
	return ""
}

func (x *InspectResponse) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *InspectResponse) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *InspectResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *InspectResponse) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

func (x *InspectResponse) GetExitCode() uint32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *InspectResponse) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *InspectResponse) GetNetworkRules() []*NetworkRule {
	if x != nil {
		return x.NetworkRules
	}
	return nil
}

func (x *InspectResponse) GetDagPath() []*DagNode {
	if x != nil {
		return x.DagPath
	}
	return nil
}

func (x *InspectResponse) GetPolicyDecisions() map[string]string {
	if x != nil {
		return x.PolicyDecisions
	}
	return nil
}

func (x *InspectResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_nimbus_runtime_proto protoreflect.FileDescriptor

const file_nimbus_runtime_proto_rawDesc = "" +
	"\n" +
	"\x14nimbus/runtime.proto\x12\x0enimbus.runtime\"K\n" +
	"\x10PullImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x1a\n" +
	"\bregistry\x18\x02 \x01(\tR\bregistry\"\x86\x01\n" +
	"\x11PullImageResponse\x12\x1f\n" +
	"\vroot_digest\x18\x01 \x01(\tR\n" +
	"rootDigest\x12!\n" +
	"\fbytes_stored\x18\x02 \x01(\x03R\vbytesStored\x12-\n" +
	"\x12bytes_deduplicated\x18\x03 \x01(\x03R\x11bytesDeduplicated\"\xd3\x03\n" +
	"\n" +
	"RunRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vroot_digest\x18\x02 \x01(\tR\n" +
	"rootDigest\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x125\n" +
	"\x03env\x18\x05 \x03(\v2#.nimbus.runtime.RunRequest.EnvEntryR\x03env\x12%\n" +
	"\x0ecpu_millicores\x18\x06 \x01(\x04R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\a \x01(\x04R\vmemoryBytes\x12!\n" +
	"\fnetwork_mode\x18\b \x01(\tR\vnetworkMode\x12@\n" +
	"\rnetwork_rules\x18\t \x03(\v2\x1b.nimbus.runtime.NetworkRuleR\fnetworkRules\x12!\n" +
	"\fkernel_image\x18\n" +
	" \x01(\tR\vkernelImage\x12\x1f\n" +
	"\vworking_dir\x18\v \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\vNetworkRule\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x17\n" +
	"\ato_host\x18\x04 \x01(\tR\x06toHost\x12\x1d\n" +
	"\n" +
	"from_cidrs\x18\x05 \x03(\tR\tfromCidrs\"s\n" +
	"\vRunResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12!\n" +
	"\fbackend_used\x18\x03 \x01(\tR\vbackendUsed\x12\x1f\n" +
	"\vinternal_ip\x18\x04 \x01(\tR\n" +
	"internalIp\"\x1d\n" +
	"\vStopRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\fStopResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12GetWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\x01\n" +
	"\x0eWorkloadStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\rR\bexitCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x1f\n" +
	"\vinternal_ip\x18\x06 \x01(\tR\n" +
	"internalIp\x12)\n" +
	"\x10network_isolated\x18\a \x01(\bR\x0fnetworkIsolated\"\x16\n" +
	"\x14ListWorkloadsRequest\"U\n" +
	"\x15ListWorkloadsResponse\x12<\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1e.nimbus.runtime.WorkloadStatusR\tworkloads\"e\n" +
	"\x11StreamLogsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x12\n" +
	"\x04tail\x18\x03 \x01(\x03R\x04tail\x12\x14\n" +
	"\x05since\x18\x04 \x01(\x03R\x05since\"T\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\bR\x06stderr\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"6\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xc7\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.nimbus.runtime.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\vExecRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\"[\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\"\x94\x03\n" +
	"\rAttachMessage\x120\n" +
	"\x04open\x18\x01 \x01(\v2\x1a.nimbus.runtime.AttachOpenH\x00R\x04open\x123\n" +
	"\x05stdin\x18\x02 \x01(\v2\x1b.nimbus.runtime.AttachStdinH\x00R\x05stdin\x12=\n" +
	"\tstdin_eof\x18\x03 \x01(\v2\x1e.nimbus.runtime.AttachStdinEofH\x00R\bstdinEof\x126\n" +
	"\x06stdout\x18\x04 \x01(\v2\x1c.nimbus.runtime.AttachStdoutH\x00R\x06stdout\x126\n" +
	"\x06stderr\x18\x05 \x01(\v2\x1c.nimbus.runtime.AttachStderrH\x00R\x06stderr\x120\n" +
	"\x04exit\x18\x06 \x01(\v2\x1a.nimbus.runtime.AttachExitH\x00R\x04exit\x123\n" +
	"\x05error\x18\a \x01(\v2\x1b.nimbus.runtime.AttachErrorH\x00R\x05errorB\x06\n" +
	"\x04body\"\xd7\x01\n" +
	"\n" +
	"AttachOpen\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x125\n" +
	"\x03env\x18\x03 \x03(\v2#.nimbus.runtime.AttachOpen.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\vAttachStdin\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x10\n" +
	"\x0eAttachStdinEof\"\"\n" +
	"\fAttachStdout\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\fAttachStderr\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x84\x01\n" +
	"\n" +
	"AttachExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\x05R\x06signal\x12\"\n" +
	"\rhas_exit_code\x18\x03 \x01(\bR\vhasExitCode\x12\x1d\n" +
	"\n" +
	"has_signal\x18\x04 \x01(\bR\thasSignal\"'\n" +
	"\vAttachError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x0fHasImageRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\"K\n" +
	"\x10HasImageResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vroot_digest\x18\x02 \x01(\tR\n" +
	"rootDigest\"\x13\n" +
	"\x11ListImagesRequest\"G\n" +
	"\x12ListImagesResponse\x121\n" +
	"\x06images\x18\x01 \x03(\v2\x19.nimbus.runtime.ImageInfoR\x06images\"\x87\x01\n" +
	"\tImageInfo\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x1f\n" +
	"\vroot_digest\x18\x02 \x01(\tR\n" +
	"rootDigest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"5\n" +
	"\x12RemoveImageRequest\x12\x1f\n" +
	"\vroot_digest\x18\x01 \x01(\tR\n" +
	"rootDigest\"P\n" +
	"\x13RemoveImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vbytes_freed\x18\x02 \x01(\x03R\n" +
	"bytesFreed\"\x15\n" +
	"\x13DagStoreInfoRequest\"\xb8\x01\n" +
	"\x14DagStoreInfoResponse\x12\x1e\n" +
	"\n" +
	"mountpoint\x18\x01 \x01(\tR\n" +
	"mountpoint\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1f\n" +
	"\vtotal_nodes\x18\x03 \x01(\x03R\n" +
	"totalNodes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vinodes_used\x18\x05 \x01(\x03R\n" +
	"inodesUsed\"e\n" +
	"\x12PortForwardRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"%\n" +
	"\x0fPortForwardData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"q\n" +
	"\x15UpdateWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0ecpu_millicores\x18\x02 \x01(\x04R\rcpuMillicores\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\"2\n" +
	"\x16UpdateWorkloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x17GetWorkloadStatsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe1\x01\n" +
	"\rWorkloadStats\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x01R\x0fcpuUsagePercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\x04 \x01(\x04R\tdiskBytes\x12(\n" +
	"\x10network_rx_bytes\x18\x05 \x01(\x04R\x0enetworkRxBytes\x12(\n" +
	"\x10network_tx_bytes\x18\x06 \x01(\x04R\x0enetworkTxBytes\" \n" +
	"\x0eInspectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\aDagNode\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"\xc7\x04\n" +
	"\x0fInspectResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x1d\n" +
	"\n" +
	"image_root\x18\x04 \x01(\tR\timageRoot\x12\x1f\n" +
	"\vinternal_ip\x18\x05 \x01(\tR\n" +
	"internalIp\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\rR\x03pid\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x1b\n" +
	"\texit_time\x18\b \x01(\x03R\bexitTime\x12\x1b\n" +
	"\texit_code\x18\t \x01(\rR\bexitCode\x12\x18\n" +
	"\acommand\x18\n" +
	" \x03(\tR\acommand\x12@\n" +
	"\rnetwork_rules\x18\v \x03(\v2\x1b.nimbus.runtime.NetworkRuleR\fnetworkRules\x122\n" +
	"\bdag_path\x18\f \x03(\v2\x17.nimbus.runtime.DagNodeR\adagPath\x12_\n" +
	"\x10policy_decisions\x18\r \x03(\v24.nimbus.runtime.InspectResponse.PolicyDecisionsEntryR\x0fpolicyDecisions\x12\x14\n" +
	"\x05found\x18\x0e \x01(\bR\x05found\x1aB\n" +
	"\x14PolicyDecisionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x99\v\n" +
	"\aRuntime\x12P\n" +
	"\tPullImage\x12 .nimbus.runtime.PullImageRequest\x1a!.nimbus.runtime.PullImageResponse\x12F\n" +
	"\vRunWorkload\x12\x1a.nimbus.runtime.RunRequest\x1a\x1b.nimbus.runtime.RunResponse\x12I\n" +
	"\fStopWorkload\x12\x1b.nimbus.runtime.StopRequest\x1a\x1c.nimbus.runtime.StopResponse\x12Q\n" +
	"\vGetWorkload\x12\".nimbus.runtime.GetWorkloadRequest\x1a\x1e.nimbus.runtime.WorkloadStatus\x12\\\n" +
	"\rListWorkloads\x12$.nimbus.runtime.ListWorkloadsRequest\x1a%.nimbus.runtime.ListWorkloadsResponse\x12K\n" +
	"\n" +
	"StreamLogs\x12!.nimbus.runtime.StreamLogsRequest\x1a\x18.nimbus.runtime.LogChunk0\x01\x12L\n" +
	"\fStreamEvents\x12#.nimbus.runtime.StreamEventsRequest\x1a\x15.nimbus.runtime.Event0\x01\x12K\n" +
	"\x0eExecInWorkload\x12\x1b.nimbus.runtime.ExecRequest\x1a\x1c.nimbus.runtime.ExecResponse\x12R\n" +
	"\x0fInspectWorkload\x12\x1e.nimbus.runtime.InspectRequest\x1a\x1f.nimbus.runtime.InspectResponse\x12R\n" +
	"\x0eAttachWorkload\x12\x1d.nimbus.runtime.AttachMessage\x1a\x1d.nimbus.runtime.AttachMessage(\x010\x01\x12M\n" +
	"\bHasImage\x12\x1f.nimbus.runtime.HasImageRequest\x1a .nimbus.runtime.HasImageResponse\x12S\n" +
	"\n" +
	"ListImages\x12!.nimbus.runtime.ListImagesRequest\x1a\".nimbus.runtime.ListImagesResponse\x12V\n" +
	"\vRemoveImage\x12\".nimbus.runtime.RemoveImageRequest\x1a#.nimbus.runtime.RemoveImageResponse\x12Y\n" +
	"\fDagStoreInfo\x12#.nimbus.runtime.DagStoreInfoRequest\x1a$.nimbus.runtime.DagStoreInfoResponse\x12T\n" +
	"\vPortForward\x12\".nimbus.runtime.PortForwardRequest\x1a\x1f.nimbus.runtime.PortForwardData0\x01\x12_\n" +
	"\x0eUpdateWorkload\x12%.nimbus.runtime.UpdateWorkloadRequest\x1a&.nimbus.runtime.UpdateWorkloadResponse\x12Z\n" +
	"\x10GetWorkloadStats\x12'.nimbus.runtime.GetWorkloadStatsRequest\x1a\x1d.nimbus.runtime.WorkloadStatsB(Z&nimbus/protoapi/nimbus/runtime;runtimeb\x06proto3"

var (
	file_nimbus_runtime_proto_rawDescOnce sync.Once
	file_nimbus_runtime_proto_rawDescData []byte
)

func file_nimbus_runtime_proto_rawDescGZIP() []byte {
	file_nimbus_runtime_proto_rawDescOnce.Do(func() {
		file_nimbus_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nimbus_runtime_proto_rawDesc), len(file_nimbus_runtime_proto_rawDesc)))
	})
	return file_nimbus_runtime_proto_rawDescData
}

var file_nimbus_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_nimbus_runtime_proto_goTypes = []any{
	(*PullImageRequest)(nil),        // 0: nimbus.runtime.PullImageRequest
	(*PullImageResponse)(nil),       // 1: nimbus.runtime.PullImageResponse
	(*RunRequest)(nil),              // 2: nimbus.runtime.RunRequest
	(*NetworkRule)(nil),             // 3: nimbus.runtime.NetworkRule
	(*RunResponse)(nil),             // 4: nimbus.runtime.RunResponse
	(*StopRequest)(nil),             // 5: nimbus.runtime.StopRequest
	(*StopResponse)(nil),            // 6: nimbus.runtime.StopResponse
	(*GetWorkloadRequest)(nil),      // 7: nimbus.runtime.GetWorkloadRequest
	(*WorkloadStatus)(nil),          // 8: nimbus.runtime.WorkloadStatus
	(*ListWorkloadsRequest)(nil),    // 9: nimbus.runtime.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),   // 10: nimbus.runtime.ListWorkloadsResponse
	(*StreamLogsRequest)(nil),       // 11: nimbus.runtime.StreamLogsRequest
	(*LogChunk)(nil),                // 12: nimbus.runtime.LogChunk
	(*StreamEventsRequest)(nil),     // 13: nimbus.runtime.StreamEventsRequest
	(*Event)(nil),                   // 14: nimbus.runtime.Event
	(*ExecRequest)(nil),             // 15: nimbus.runtime.ExecRequest
	(*ExecResponse)(nil),            // 16: nimbus.runtime.ExecResponse
	(*AttachMessage)(nil),           // 17: nimbus.runtime.AttachMessage
	(*AttachOpen)(nil),              // 18: nimbus.runtime.AttachOpen
	(*AttachStdin)(nil),             // 19: nimbus.runtime.AttachStdin
	(*AttachStdinEof)(nil),          // 20: nimbus.runtime.AttachStdinEof
	(*AttachStdout)(nil),            // 21: nimbus.runtime.AttachStdout
	(*AttachStderr)(nil),            // 22: nimbus.runtime.AttachStderr
	(*AttachExit)(nil),              // 23: nimbus.runtime.AttachExit
	(*AttachError)(nil),             // 24: nimbus.runtime.AttachError
	(*HasImageRequest)(nil),         // 25: nimbus.runtime.HasImageRequest
	(*HasImageResponse)(nil),        // 26: nimbus.runtime.HasImageResponse
	(*ListImagesRequest)(nil),       // 27: nimbus.runtime.ListImagesRequest
	(*ListImagesResponse)(nil),      // 28: nimbus.runtime.ListImagesResponse
	(*ImageInfo)(nil),               // 29: nimbus.runtime.ImageInfo
	(*RemoveImageRequest)(nil),      // 30: nimbus.runtime.RemoveImageRequest
	(*RemoveImageResponse)(nil),     // 31: nimbus.runtime.RemoveImageResponse
	(*DagStoreInfoRequest)(nil),     // 32: nimbus.runtime.DagStoreInfoRequest
	(*DagStoreInfoResponse)(nil),    // 33: nimbus.runtime.DagStoreInfoResponse
	(*PortForwardRequest)(nil),      // 34: nimbus.runtime.PortForwardRequest
	(*PortForwardData)(nil),         // 35: nimbus.runtime.PortForwardData
	(*UpdateWorkloadRequest)(nil),   // 36: nimbus.runtime.UpdateWorkloadRequest
	(*UpdateWorkloadResponse)(nil),  // 37: nimbus.runtime.UpdateWorkloadResponse
	(*GetWorkloadStatsRequest)(nil), // 38: nimbus.runtime.GetWorkloadStatsRequest
	(*WorkloadStats)(nil),           // 39: nimbus.runtime.WorkloadStats
	(*InspectRequest)(nil),          // 40: nimbus.runtime.InspectRequest
	(*DagNode)(nil),                 // 41: nimbus.runtime.DagNode
	(*InspectResponse)(nil),         // 42: nimbus.runtime.InspectResponse
	nil,                             // 43: nimbus.runtime.RunRequest.EnvEntry
	nil,                             // 44: nimbus.runtime.Event.MetadataEntry
	nil,                             // 45: nimbus.runtime.AttachOpen.EnvEntry
	nil,                             // 46: nimbus.runtime.InspectResponse.PolicyDecisionsEntry
}
var file_nimbus_runtime_proto_depIdxs = []int32{
	43, // 0: nimbus.runtime.RunRequest.env:type_name -> nimbus.runtime.RunRequest.EnvEntry
	3,  // 1: nimbus.runtime.RunRequest.network_rules:type_name -> nimbus.runtime.NetworkRule
	8,  // 2: nimbus.runtime.ListWorkloadsResponse.workloads:type_name -> nimbus.runtime.WorkloadStatus
	44, // 3: nimbus.runtime.Event.metadata:type_name -> nimbus.runtime.Event.MetadataEntry
	18, // 4: nimbus.runtime.AttachMessage.open:type_name -> nimbus.runtime.AttachOpen
	19, // 5: nimbus.runtime.AttachMessage.stdin:type_name -> nimbus.runtime.AttachStdin
	20, // 6: nimbus.runtime.AttachMessage.stdin_eof:type_name -> nimbus.runtime.AttachStdinEof
	21, // 7: nimbus.runtime.AttachMessage.stdout:type_name -> nimbus.runtime.AttachStdout
	22, // 8: nimbus.runtime.AttachMessage.stderr:type_name -> nimbus.runtime.AttachStderr
	23, // 9: nimbus.runtime.AttachMessage.exit:type_name -> nimbus.runtime.AttachExit
	24, // 10: nimbus.runtime.AttachMessage.error:type_name -> nimbus.runtime.AttachError
	45, // 11: nimbus.runtime.AttachOpen.env:type_name -> nimbus.runtime.AttachOpen.EnvEntry
	29, // 12: nimbus.runtime.ListImagesResponse.images:type_name -> nimbus.runtime.ImageInfo
	3,  // 13: nimbus.runtime.InspectResponse.network_rules:type_name -> nimbus.runtime.NetworkRule
	41, // 14: nimbus.runtime.InspectResponse.dag_path:type_name -> nimbus.runtime.DagNode
	46, // 15: nimbus.runtime.InspectResponse.policy_decisions:type_name -> nimbus.runtime.InspectResponse.PolicyDecisionsEntry
	0,  // 16: nimbus.runtime.Runtime.PullImage:input_type -> nimbus.runtime.PullImageRequest
	2,  // 17: nimbus.runtime.Runtime.RunWorkload:input_type -> nimbus.runtime.RunRequest
	5,  // 18: nimbus.runtime.Runtime.StopWorkload:input_type -> nimbus.runtime.StopRequest
	7,  // 19: nimbus.runtime.Runtime.GetWorkload:input_type -> nimbus.runtime.GetWorkloadRequest
	9,  // 20: nimbus.runtime.Runtime.ListWorkloads:input_type -> nimbus.runtime.ListWorkloadsRequest
	11, // 21: nimbus.runtime.Runtime.StreamLogs:input_type -> nimbus.runtime.StreamLogsRequest
	13, // 22: nimbus.runtime.Runtime.StreamEvents:input_type -> nimbus.runtime.StreamEventsRequest
	15, // 23: nimbus.runtime.Runtime.ExecInWorkload:input_type -> nimbus.runtime.ExecRequest
	40, // 24: nimbus.runtime.Runtime.InspectWorkload:input_type -> nimbus.runtime.InspectRequest
	17, // 25: nimbus.runtime.Runtime.AttachWorkload:input_type -> nimbus.runtime.AttachMessage
	25, // 26: nimbus.runtime.Runtime.HasImage:input_type -> nimbus.runtime.HasImageRequest
	27, // 27: nimbus.runtime.Runtime.ListImages:input_type -> nimbus.runtime.ListImagesRequest
	30, // 28: nimbus.runtime.Runtime.RemoveImage:input_type -> nimbus.runtime.RemoveImageRequest
	32, // 29: nimbus.runtime.Runtime.DagStoreInfo:input_type -> nimbus.runtime.DagStoreInfoRequest
	34, // 30: nimbus.runtime.Runtime.PortForward:input_type -> nimbus.runtime.PortForwardRequest
	36, // 31: nimbus.runtime.Runtime.UpdateWorkload:input_type -> nimbus.runtime.UpdateWorkloadRequest
	38, // 32: nimbus.runtime.Runtime.GetWorkloadStats:input_type -> nimbus.runtime.GetWorkloadStatsRequest
	1,  // 33: nimbus.runtime.Runtime.PullImage:output_type -> nimbus.runtime.PullImageResponse
	4,  // 34: nimbus.runtime.Runtime.RunWorkload:output_type -> nimbus.runtime.RunResponse
	6,  // 35: nimbus.runtime.Runtime.StopWorkload:output_type -> nimbus.runtime.StopResponse
	8,  // 36: nimbus.runtime.Runtime.GetWorkload:output_type -> nimbus.runtime.WorkloadStatus
	10, // 37: nimbus.runtime.Runtime.ListWorkloads:output_type -> nimbus.runtime.ListWorkloadsResponse
	12, // 38: nimbus.runtime.Runtime.StreamLogs:output_type -> nimbus.runtime.LogChunk
	14, // 39: nimbus.runtime.Runtime.StreamEvents:output_type -> nimbus.runtime.Event
	16, // 40: nimbus.runtime.Runtime.ExecInWorkload:output_type -> nimbus.runtime.ExecResponse
	42, // 41: nimbus.runtime.Runtime.InspectWorkload:output_type -> nimbus.runtime.InspectResponse
	17, // 42: nimbus.runtime.Runtime.AttachWorkload:output_type -> nimbus.runtime.AttachMessage
	26, // 43: nimbus.runtime.Runtime.HasImage:output_type -> nimbus.runtime.HasImageResponse
	28, // 44: nimbus.runtime.Runtime.ListImages:output_type -> nimbus.runtime.ListImagesResponse
	31, // 45: nimbus.runtime.Runtime.RemoveImage:output_type -> nimbus.runtime.RemoveImageResponse
	33, // 46: nimbus.runtime.Runtime.DagStoreInfo:output_type -> nimbus.runtime.DagStoreInfoResponse
	35, // 47: nimbus.runtime.Runtime.PortForward:output_type -> nimbus.runtime.PortForwardData
	37, // 48: nimbus.runtime.Runtime.UpdateWorkload:output_type -> nimbus.runtime.UpdateWorkloadResponse
	39, // 49: nimbus.runtime.Runtime.GetWorkloadStats:output_type -> nimbus.runtime.WorkloadStats
	33, // [33:50] is the sub-list for method output_type
	16, // [16:33] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_nimbus_runtime_proto_init() }
func file_nimbus_runtime_proto_init() {
	if File_nimbus_runtime_proto != nil {
		return
	}
	file_nimbus_runtime_proto_msgTypes[17].OneofWrappers = []any{
		(*AttachMessage_Open)(nil),
		(*AttachMessage_Stdin)(nil),
		(*AttachMessage_StdinEof)(nil),
		(*AttachMessage_Stdout)(nil),
		(*AttachMessage_Stderr)(nil),
		(*AttachMessage_Exit)(nil),
		(*AttachMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nimbus_runtime_proto_rawDesc), len(file_nimbus_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nimbus_runtime_proto_goTypes,
		DependencyIndexes: file_nimbus_runtime_proto_depIdxs,
		MessageInfos:      file_nimbus_runtime_proto_msgTypes,
	}.Build()
	File_nimbus_runtime_proto = out.File
	file_nimbus_runtime_proto_goTypes = nil
	file_nimbus_runtime_proto_depIdxs = nil
}
