// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: nimbus/runtime.proto

package runtime

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_PullImage_FullMethodName        = "/nimbus.runtime.Runtime/PullImage"
	Runtime_RunWorkload_FullMethodName      = "/nimbus.runtime.Runtime/RunWorkload"
	Runtime_StopWorkload_FullMethodName     = "/nimbus.runtime.Runtime/StopWorkload"
	Runtime_GetWorkload_FullMethodName      = "/nimbus.runtime.Runtime/GetWorkload"
	Runtime_ListWorkloads_FullMethodName    = "/nimbus.runtime.Runtime/ListWorkloads"
	Runtime_StreamLogs_FullMethodName       = "/nimbus.runtime.Runtime/StreamLogs"
	Runtime_StreamEvents_FullMethodName     = "/nimbus.runtime.Runtime/StreamEvents"
	Runtime_ExecInWorkload_FullMethodName   = "/nimbus.runtime.Runtime/ExecInWorkload"
	Runtime_InspectWorkload_FullMethodName  = "/nimbus.runtime.Runtime/InspectWorkload"
	Runtime_AttachWorkload_FullMethodName   = "/nimbus.runtime.Runtime/AttachWorkload"
	Runtime_HasImage_FullMethodName         = "/nimbus.runtime.Runtime/HasImage"
	Runtime_ListImages_FullMethodName       = "/nimbus.runtime.Runtime/ListImages"
	Runtime_RemoveImage_FullMethodName      = "/nimbus.runtime.Runtime/RemoveImage"
	Runtime_DagStoreInfo_FullMethodName     = "/nimbus.runtime.Runtime/DagStoreInfo"
	Runtime_PortForward_FullMethodName      = "/nimbus.runtime.Runtime/PortForward"
	Runtime_UpdateWorkload_FullMethodName   = "/nimbus.runtime.Runtime/UpdateWorkload"
	Runtime_GetWorkloadStats_FullMethodName = "/nimbus.runtime.Runtime/GetWorkloadStats"
	Runtime_RunCompose_FullMethodName       = "/nimbus.runtime.Runtime/RunCompose"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error)
	RunWorkload(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	StopWorkload(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadStatus, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	ExecInWorkload(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	InspectWorkload(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	// Interactive attach to a workload's stdio. The first request
	// opens the stream; subsequent messages carry stdin/eof
	// (client -> server) and stdout/stderr/exit (server -> client).
	// Used by `nimbusctl workload run alpine:3.18 -- /bin/sh` and
	// similar interactive workloads on microVM backends.
	AttachWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachMessage, AttachMessage], error)
	// Image management
	HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error)
	DagStoreInfo(ctx context.Context, in *DagStoreInfoRequest, opts ...grpc.CallOption) (*DagStoreInfoResponse, error)
	// Port forwarding
	PortForward(ctx context.Context, in *PortForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortForwardData], error)
	// Workload resource updates
	UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error)
	// Workload statistics
	GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*WorkloadStats, error)
	// Batch-launch multiple services from a Compose project.
	// Services are created in dependency order (depends_on).
	// On first failure, returns the error; already-started
	// workloads are NOT automatically stopped (the client
	// should call StopWorkload for rollback).
	RunCompose(ctx context.Context, in *RunComposeRequest, opts ...grpc.CallOption) (*RunComposeResponse, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) PullImage(ctx context.Context, in *PullImageRequest, opts ...grpc.CallOption) (*PullImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullImageResponse)
	err := c.cc.Invoke(ctx, Runtime_PullImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RunWorkload(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, Runtime_RunWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StopWorkload(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, Runtime_StopWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*WorkloadStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStatus)
	err := c.cc.Invoke(ctx, Runtime_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[0], Runtime_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *runtimeClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[1], Runtime_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamEventsClient = grpc.ServerStreamingClient[Event]

func (c *runtimeClient) ExecInWorkload(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, Runtime_ExecInWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) InspectWorkload(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, Runtime_InspectWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) AttachWorkload(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachMessage, AttachMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[2], Runtime_AttachWorkload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachMessage, AttachMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachWorkloadClient = grpc.BidiStreamingClient[AttachMessage, AttachMessage]

func (c *runtimeClient) HasImage(ctx context.Context, in *HasImageRequest, opts ...grpc.CallOption) (*HasImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasImageResponse)
	err := c.cc.Invoke(ctx, Runtime_HasImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, Runtime_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveImage(ctx context.Context, in *RemoveImageRequest, opts ...grpc.CallOption) (*RemoveImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveImageResponse)
	err := c.cc.Invoke(ctx, Runtime_RemoveImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) DagStoreInfo(ctx context.Context, in *DagStoreInfoRequest, opts ...grpc.CallOption) (*DagStoreInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DagStoreInfoResponse)
	err := c.cc.Invoke(ctx, Runtime_DagStoreInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PortForward(ctx context.Context, in *PortForwardRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortForwardData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Runtime_ServiceDesc.Streams[3], Runtime_PortForward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortForwardRequest, PortForwardData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardClient = grpc.ServerStreamingClient[PortForwardData]

func (c *runtimeClient) UpdateWorkload(ctx context.Context, in *UpdateWorkloadRequest, opts ...grpc.CallOption) (*UpdateWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkloadResponse)
	err := c.cc.Invoke(ctx, Runtime_UpdateWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetWorkloadStats(ctx context.Context, in *GetWorkloadStatsRequest, opts ...grpc.CallOption) (*WorkloadStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStats)
	err := c.cc.Invoke(ctx, Runtime_GetWorkloadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RunCompose(ctx context.Context, in *RunComposeRequest, opts ...grpc.CallOption) (*RunComposeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunComposeResponse)
	err := c.cc.Invoke(ctx, Runtime_RunCompose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error)
	RunWorkload(context.Context, *RunRequest) (*RunResponse, error)
	StopWorkload(context.Context, *StopRequest) (*StopResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*WorkloadStatus, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error
	ExecInWorkload(context.Context, *ExecRequest) (*ExecResponse, error)
	InspectWorkload(context.Context, *InspectRequest) (*InspectResponse, error)
	// Interactive attach to a workload's stdio. The first request
	// opens the stream; subsequent messages carry stdin/eof
	// (client -> server) and stdout/stderr/exit (server -> client).
	// Used by `nimbusctl workload run alpine:3.18 -- /bin/sh` and
	// similar interactive workloads on microVM backends.
	AttachWorkload(grpc.BidiStreamingServer[AttachMessage, AttachMessage]) error
	// Image management
	HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error)
	DagStoreInfo(context.Context, *DagStoreInfoRequest) (*DagStoreInfoResponse, error)
	// Port forwarding
	PortForward(*PortForwardRequest, grpc.ServerStreamingServer[PortForwardData]) error
	// Workload resource updates
	UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error)
	// Workload statistics
	GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*WorkloadStats, error)
	// Batch-launch multiple services from a Compose project.
	// Services are created in dependency order (depends_on).
	// On first failure, returns the error; already-started
	// workloads are NOT automatically stopped (the client
	// should call StopWorkload for rollback).
	RunCompose(context.Context, *RunComposeRequest) (*RunComposeResponse, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) PullImage(context.Context, *PullImageRequest) (*PullImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedRuntimeServer) RunWorkload(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunWorkload not implemented")
}
func (UnimplementedRuntimeServer) StopWorkload(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopWorkload not implemented")
}
func (UnimplementedRuntimeServer) GetWorkload(context.Context, *GetWorkloadRequest) (*WorkloadStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedRuntimeServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedRuntimeServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedRuntimeServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedRuntimeServer) ExecInWorkload(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecInWorkload not implemented")
}
func (UnimplementedRuntimeServer) InspectWorkload(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectWorkload not implemented")
}
func (UnimplementedRuntimeServer) AttachWorkload(grpc.BidiStreamingServer[AttachMessage, AttachMessage]) error {
	return status.Error(codes.Unimplemented, "method AttachWorkload not implemented")
}
func (UnimplementedRuntimeServer) HasImage(context.Context, *HasImageRequest) (*HasImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasImage not implemented")
}
func (UnimplementedRuntimeServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedRuntimeServer) RemoveImage(context.Context, *RemoveImageRequest) (*RemoveImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveImage not implemented")
}
func (UnimplementedRuntimeServer) DagStoreInfo(context.Context, *DagStoreInfoRequest) (*DagStoreInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DagStoreInfo not implemented")
}
func (UnimplementedRuntimeServer) PortForward(*PortForwardRequest, grpc.ServerStreamingServer[PortForwardData]) error {
	return status.Error(codes.Unimplemented, "method PortForward not implemented")
}
func (UnimplementedRuntimeServer) UpdateWorkload(context.Context, *UpdateWorkloadRequest) (*UpdateWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkload not implemented")
}
func (UnimplementedRuntimeServer) GetWorkloadStats(context.Context, *GetWorkloadStatsRequest) (*WorkloadStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkloadStats not implemented")
}
func (UnimplementedRuntimeServer) RunCompose(context.Context, *RunComposeRequest) (*RunComposeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCompose not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PullImage(ctx, req.(*PullImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RunWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RunWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RunWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RunWorkload(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StopWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StopWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StopWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StopWorkload(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamLogsServer = grpc.ServerStreamingServer[LogChunk]

func _Runtime_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_StreamEventsServer = grpc.ServerStreamingServer[Event]

func _Runtime_ExecInWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ExecInWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ExecInWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ExecInWorkload(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_InspectWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).InspectWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_InspectWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).InspectWorkload(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_AttachWorkload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RuntimeServer).AttachWorkload(&grpc.GenericServerStream[AttachMessage, AttachMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_AttachWorkloadServer = grpc.BidiStreamingServer[AttachMessage, AttachMessage]

func _Runtime_HasImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).HasImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_HasImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).HasImage(ctx, req.(*HasImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveImage(ctx, req.(*RemoveImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_DagStoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DagStoreInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).DagStoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_DagStoreInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).DagStoreInfo(ctx, req.(*DagStoreInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PortForward_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PortForwardRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServer).PortForward(m, &grpc.GenericServerStream[PortForwardRequest, PortForwardData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Runtime_PortForwardServer = grpc.ServerStreamingServer[PortForwardData]

func _Runtime_UpdateWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).UpdateWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_UpdateWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).UpdateWorkload(ctx, req.(*UpdateWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetWorkloadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetWorkloadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetWorkloadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetWorkloadStats(ctx, req.(*GetWorkloadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RunCompose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunComposeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RunCompose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RunCompose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RunCompose(ctx, req.(*RunComposeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nimbus.runtime.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PullImage",
			Handler:    _Runtime_PullImage_Handler,
		},
		{
			MethodName: "RunWorkload",
			Handler:    _Runtime_RunWorkload_Handler,
		},
		{
			MethodName: "StopWorkload",
			Handler:    _Runtime_StopWorkload_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _Runtime_GetWorkload_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _Runtime_ListWorkloads_Handler,
		},
		{
			MethodName: "ExecInWorkload",
			Handler:    _Runtime_ExecInWorkload_Handler,
		},
		{
			MethodName: "InspectWorkload",
			Handler:    _Runtime_InspectWorkload_Handler,
		},
		{
			MethodName: "HasImage",
			Handler:    _Runtime_HasImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _Runtime_ListImages_Handler,
		},
		{
			MethodName: "RemoveImage",
			Handler:    _Runtime_RemoveImage_Handler,
		},
		{
			MethodName: "DagStoreInfo",
			Handler:    _Runtime_DagStoreInfo_Handler,
		},
		{
			MethodName: "UpdateWorkload",
			Handler:    _Runtime_UpdateWorkload_Handler,
		},
		{
			MethodName: "GetWorkloadStats",
			Handler:    _Runtime_GetWorkloadStats_Handler,
		},
		{
			MethodName: "RunCompose",
			Handler:    _Runtime_RunCompose_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _Runtime_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Runtime_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AttachWorkload",
			Handler:       _Runtime_AttachWorkload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "PortForward",
			Handler:       _Runtime_PortForward_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "nimbus/runtime.proto",
}
